#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "//---------------------------------------------------------------------//"
echo "Danh sach cac syntax trong LarVPS"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-26"
echo 

echo "
Global
-------------------------------------------------------------------------

larvps: Hien thi menu LarVPS
larvps -i/info: Xem thong tin VPS
larvps -ic : Xem thông tin cài đặt
larvps -sv: Xem trạng thái các Service
larvps -e/-l: Xem 15 dòng log đầu tiên
larvps -lf: Xem toàn bộ log
larvps -pa: Xem port Admin hiện tại
larvps -po: Xem các port đang mở
larvps ram: Xem dung lượng ram hiện tại

Domain
-------------------------------------------------------------------------
larvps domain create: Thêm domain mới
larvps -ic {domain}: xem thông tin cài đặt của domain
larvps chmod A: phân lại quyền cho domain A

Nginx
-------------------------------------------------------------------------

larvps nginx -r/restart: Khởi động lại Nginx
larvps nginx -s/status: Xem trạng thái Nginx
larvps nginx -l/log: Xem log Nginx
larvps nginx -ll/clear-log: Xóa log Nginx

PHP-FPM
-------------------------------------------------------------------------

larvps php -r/restart: Khởi động lại PHP-FPM
larvps php -s/status: Xem trạng thái PHP-FPM
larvps php -l/log: Xem log PHP-FPM
larvps php -ll/clear-log: Xóa log PHP-FPM

MYSQL
-------------------------------------------------------------------------

larvps mysql -r/restart : Khởi động lại MariaDB
larvps mysql -s/status: Xem trạng thái MariaDB
larvps mysql -l/log: Xem log MariaDB
larvps mysql -ll/clear-log: Xóa log MariaDB

Hướng dẫn sử dụng:
-------------------------------------------------------------------------

Ví dụ sử dung để restart lại Nginx:
larvps nginx -r
larvps nginx restart
"
