#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "//---------------------------------------------------------------------//"
echo "Restart Service"
echo "-------------------------------------------------------------------------"
echo 
options=(
    "Nginx"
    "PHP-FPM"
    "MySQL"
    "SSHD"
    "Fail2ban"
    "Crond"
)
select=0
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            select="nginx"
            break;
            ;;
        "${options[1]}")
            select="php-fpm"
            break;
            ;;
        "${options[2]}")
            select="mysql"
            break;
            ;;
        "${options[3]}")
            select="sshd"
            break;
            ;;
        "${options[4]}")
            select="fail2ban"
            break;
            ;;
        "${options[5]}")
			select="crond"
            break;
            ;;
        *) action_syntax_manager;;
    esac
done

if [[ "$select" = "nginx" ]]; then
nginx -t && systemctl restart nginx.service
fi

if [[ "$select" = "php-fpm" ]]; then
systemctl restart php-fpm.service
fi

if [[ "$select" = "mysql" ]]; then
systemctl restart mysql.service
fi

if [[ "$select" = "sshd" ]]; then
systemctl restart sshd.service
fi

if [[ "$select" = "fail2ban" ]]; then
systemctl restart fail2ban.service
fi

if [[ "$select" = "crond" ]]; then
systemctl restart crond.service
fi

echo "Hoan thanh."
action_syntax_manager
