#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "-//----------------------------------------------------------------------"
echo "25. Active Key > Active"
echo "-------------------------------------------------------------------------"
echo ""
read -p "Nhap Active Key cua ban [0=Thoat]: " key

if [[ "$key" = "" ]]; then
    action_active_key
fi

if [[ "$key" = "0" ]]; then
    clear
    larvps
fi

hash=$(< /dev/urandom tr -dc a-z0-9 | head -c${1:-60};echo;)
url="https://larvps.com/keys/active/$key?hash=$hash&ip=$ip"
status=$(curl -s "$url" | grep "status=" | cut -f2 -d"=")

if [[ $? -ne 0 ]]; then
    echo "Ket noi that bai"
    sleep 3
    larvps
fi

if [[ "$status" != "true" ]]; then
	clear
    echo "Active key khong dung hoac khong ton tai."
    sleep 3
    action_active_key
fi

cat > "/etc/larvps/.key.conf" <<END
key=$key
hash=$hash
END

echo "VPS cua ban da kich hoat Active Key thanh cong."
echo "Cam on ban da lua chon LarVPS."
echo "Dang tien hanh cap nhat..."
sleep 2

script_url="https://larvps.com/keys/download/$key?hash=$hash&ip=$ip"

cd
wget "$script_url" -O menu.zip
unzip -o menu.zip
clear
cd menu
mv -f larvps /usr/bin/
rm -rf /etc/larvps/menu
cd ..
mv menu /etc/larvps/
rm -rf menu.zip
rm -rf __MACOSX
echo "Da cap nhat thanh cong..."

sleep 2
clear
larvps