#!/bin/bash

status="Error"
apache2="$(systemctl status apache2.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
phpfpm="$(systemctl status php-fpm.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
mariadb="$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
if [[ "$apache2" = 'active' ]] || [[ "$phpfpm" = 'active' ]] || [[ "$mariadb" = 'active' ]]; then
status="OK"
fi

version="1.0.0"
disk=$(mount|grep ' / '|cut -d' ' -f 1)
total_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $3}' | tr -d 'a-zA-G')
use_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $4}' | tr -d 'a-zA-G')
total_ram=$(free -m | grep "Mem" | awk -F ' ' '{print $2}')
use_ram=$(free -m | grep "Mem" | awk -F ' ' '{print $3}')
total_swap=$(free -m | grep "Swap" | awk -F ' ' '{print $2}')
use_swap=$(free -m | grep "Swap" | awk -F ' ' '{print $3}')
memAvailable=$(cat /proc/meminfo | grep 'MemAvailable' |cut -f2 -d':' | xargs | cut -f1 -d' ')
totalSwap=$(cat /proc/meminfo | grep 'SwapTotal' |cut -f2 -d':' | xargs | cut -f1 -d' ')
freeSwap=$(cat /proc/meminfo | grep 'SwapFree' |cut -f2 -d':' | xargs | cut -f1 -d' ')

