#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "15. Quan ly Port > Mo Port"
echo "/-----------------------------------------------------------------------/"
echo ""
read -p "Nhap port ban muon mo [0=Thoat]: " port


if [ "$port" = "0" ]; then
    clear
    action_port
fi

if [ "$port" = "" ]; then
	clear
	echo "Ban chua nhap port."
	echo
	action_port
fi

if [[ ! $port =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Port khong dung dinh dang vui long nhap tu 2000 - 9000"
    echo
    action_port
fi

read -p "Xac nhan (y/N): " confirm

if [ "$confirm" = "y" ]; then
   	echo "Dang tien hanh port..."
   	sleep 1
    firewall-cmd --permanent --zone=public --add-port=$port/tcp
    firewall-cmd --reload
    clear
    echo "Da mo port."
    
    action_port
else
	clear
	
	action_port
fi
