#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "15. Quan ly Port > Khoa Port"
echo "-------------------------------------------------------------------------"
read -p "Nhap port ban muon khoa [0=Thoat]: " port


if [ "$port" = "0" ]; then
    clear
    action_port
fi

if [ "$port" = "" ]; then
	clear
	echo "Ban chua nhap port."
	echo
	action_port
fi

if [[ ! $port =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Port khong dung dinh dang vui long nhap tu 2000 - 9000"
    echo
    action_port
fi

read -p "Xac nhan khoa $port? (y/n): " confirm

if [ "$confirm" = "y" ]; then
   	echo "Dang tien hanh khoa port..."
   	sleep 1
    firewall-cmd --permanent --zone=public --remove-port=$port/tcp
    firewall-cmd --reload
    clear
    echo "Hoan thanh."
    echo
    action_port
else
	clear
	echo
	action_port
fi