#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "15. Quan ly Port > Danh sach Port"
echo "/-----------------------------------------------------------------------/"
echo
echo "Danh sach Port dang mo VPS:"
echo
firewall-cmd --list-ports | tr " " "\n"
# netstat -lnt | awk 'NR>2{print $4}' | grep -E '0.0.0.0:' | sed 's/.*://' | sort -n | uniq
sleep 3 
action_port