#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "//---------------------------------------------------------------------//"
echo "Kiem tra phien ban LarVPS"
echo "-------------------------------------------------------------------------"
last_version=$(curl -s https://larvps.com/scripts/info | grep "latest_version=" | cut -f2 -d'=')
date_version=$(curl -s https://larvps.com/scripts/info | grep "date_version=" | cut -f2 -d'=')
echo
echo "/-----------------------------------------------------------------------/"
echo "Hien tai: $version"
echo "Moi nhat: $last_version - $date_version"
echo "/-----------------------------------------------------------------------/"
action_larvps_update