#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "13. Quan ly Cache > Memcached" 
echo "-------------------------------------------------------------------------"
status=$(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
echo "Trang thai: $status"
echo "/-----------------------------------------------------------------------/"
echo
options=("Mo Memcached" "Tat Memcached" "Cau hinh Memcached")
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            echo "Dang tien hanh mo Memcached..."
            sleep 1
            systemctl start memcached
            systemctl enable memcached
            firewall-cmd --permanent --zone=public --add-port=11211/tcp
            firewall-cmd --reload
            clear
            echo "Da bat Memcached"
            action_cache
            ;;
        "${options[1]}")
            echo "Dang tien hanh tat Memcached..."
            sleep 1
            systemctl stop memcached
            systemctl disable memcached
            firewall-cmd --zone=public --remove-port=11211/tcp
            firewall-cmd --reload
            clear
            echo "Da tat Memcached"
            action_cache
            ;;
        "${options[2]}")
            echo "Huong Dan:"
            echo "Ctrl + O chọn Y: De luu lai thay doi cau hinh."
            echo "Dang tien hanh mo cau hinh Memcached..."
            sleep 5
            nano /etc/sysconfig/memcached
            ;;
        *) action_cache;;
    esac
done
