#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "13. Quan ly Cache > Redis cache" 
echo "-------------------------------------------------------------------------"
status=$(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
echo "Trang thai: $status"
echo "/-----------------------------------------------------------------------/"
echo
options=("Bat Redis Cache" "Tat Redis Cache" "Cau hinh Redis Cache")
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            echo "Dang tien hanh bat Redis Cache..."
            sleep 1
            systemctl enable redis.service
            systemctl start redis.service
            firewall-cmd --permanent --zone=public --add-port=6379/tcp
            firewall-cmd --reload
            clear
            echo "Da bat Redis Cache"
            action_cache
            ;;
        "${options[1]}")
            echo "Dang tien hanh tat Redis Cache..."
            sleep 1
            systemctl stop redis.service
            systemctl disable redis.service
            firewall-cmd --zone=public --remove-port=6379/tcp
            firewall-cmd --reload
            clear
            echo "Da tat Redis Cache"
            action_cache
            ;;
        "${options[2]}")
            echo "Huong Dan:"
            echo "Ctrl + O chọn Y: De luu lai thay doi cau hinh."
            echo "Dang tien hanh mo cau hinh Redis Cache..."
            sleep 5
            nano /etc/redis.conf
            ;;
        *) action_cache;;
    esac
done