#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//-------------------------------------------------------------------//"
echo "Thay doi password User"
echo "------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-8-23"
echo "/-----------------------------------------------------------------------/"
echo
read -p "Nhap ten User: " username
read -p "Nhap Password: " password

if [ "$username" = '' ] || [ "$username" = '0' ] || [ "$password" = '0' ]; then
    app_admin
fi

read -p "Xac nhan doi password cho $username? (y/n): " confirm
if [[ "$confirm" = 'y' ]]; then

	if [[ "$username" = "admin" ]]; then
		sed -i '/ad_password/d' /etc/larvps/.larvps.conf
		echo "ad_password=$password" >>  /etc/larvps/.larvps.conf
	fi

setup=$(expect -c "
spawn htpasswd /usr/share/nginx/larvps/passwd/.htpasswd $username
expect \"password\"
send \"$password\r\"
expect \"password\"
send \"$password\r\"
expect eof
")
	clear
   	echo "Hoan thanh."
   	app_admin
fi
