#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "Thay doi port Admin"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-8-23"
echo "/-----------------------------------------------------------------------/"
echo
port_open=$port_admin
echo "Port Admin hien tai: $port_open"
echo "http://$ip:$port_open/phpmyadmin"
echo "/------------------------------------------------------------------------/"
read -p "Nhap Port moi: " port_new
port_ssh=$(cat /etc/ssh/sshd_config | grep "Port " | cut -f2 -d" ")

if [ "$port_new" = "" ]; then
    app_admin
fi

if [[ ! $port_new =~ ^-?[0-9]+$ ]] || [[ "$port_new" < "2000" ]] || [[ "$port_new" > "9000" ]]; then
    clear
    echo "Port khong dung dinh dang, vui long nhap port tu 2000 - 9000"
    app_admin
fi

if [ "$port_new" != '' ] && [ "$port_new" != "$port_ssh" ] && [ "$port_new" != "$port_open" ]; then
    read -p "Xac nhan thay doi port $port_open sang port $port_new? (y/n): " confirm

    if [ "$confirm" = 'y' ]; then
        echo "Dang tien hanh thay doi port..."
        sleep 1
        # mở port bí mật
        firewall-cmd --zone=public --remove-port=$port_open/tcp
        firewall-cmd --permanent --zone=public --add-port=$port_new/tcp
        firewall-cmd --reload

        # cấu hình nginx
        sed -i '/listen/d' /etc/nginx/conf.d/default.conf
        sed -i "/server_name larvps;/a listen $port_new;" /etc/nginx/conf.d/default.conf

        nginx -t && systemctl restart nginx.service

        # luu cai hinh
        sed -i "/port_admin=/d" /etc/larvps/.larvps.conf
        echo "port_admin=$port_new" >> /etc/larvps/.larvps.conf
        
        #fail2ban
        sed -i "/port/d" /etc/fail2ban/jail.d/nginx.local
        echo "port=$port_new" >> /etc/fail2ban/jail.d/nginx.local
        fail2ban-client reload

        clear
        echo "Thay doi port thanh cong"
        app_admin

    fi
else
    clear
    echo "Vui long su dung port Admin khac."
    app_admin
fi