#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "Them user"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-8-21"
echo "/-----------------------------------------------------------------------/"
echo
read -p "Nhap ten user: " username

if [ "$username" = "" ]; then
    clear
    app_admin
fi

if [[ "$username" ]]; then
    read -p "Xac nhan them user: $username? (y/n): " confirm
    if [[ "$confirm" = 'y' ]]; then
       echo "Dang tien hanh them user..."
       sleep 1
       htpasswd /usr/share/nginx/larvps/passwd/.htpasswd $username
       clear
       echo "Da them user $username thanh cong..."
       app_admin
    else
       app_admin
    fi
fi
