#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
count=$(cat /etc/fail2ban/jail.d/nginx.local | grep maxretry | cut -f2 -d'=' | xargs)
echo "--//---------------------------------------------------------------------"
echo "4. Quan ly AppAdmin > Auth login failed"
echo "/-----------------------------------------------------------------------/"
echo "So lan cho phep: $count"
echo ""
read -p "Nhap so lan login failed se bi khoa IP [ex: 3]: " new_count

if [[ "$new_count" = '0' || "$new_count" = "" ]]; then
    app_admin
fi

sed -i "/maxretry/d" /etc/fail2ban/jail.d/nginx.local
echo "maxretry=$new_count" >> /etc/fail2ban/jail.d/nginx.local

fail2ban-client reload
clear
echo "Hoan thanh."
app_admin
