#!/bin/bash
clear
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "- 1. Quan ly Domain : $(apache2 -v | cut -f3 -d' ' | head -1) - $(systemctl status apache2.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo "//---------------------------------------------------------------------//"
echo
echo "--//---------------------------------------------------------------------"
echo "- 4. Quan ly Domain > Kiem tra trang thai service Apache"
echo "/-----------------------------------------------------------------------/"
echo ""

service=apache2

if pid=$(pgrep $service);
then
        echo "Service Apache dang hoat dong PID =" $pid | awk -F"/" '{ print $1 }'
        echo "Quay lai menu chinh..."
        sleep 10
        /usr/local/mbmenu/mbdomain

else
        echo "Service Apache khong hoat dong, in ra log loi..."
        tail /var/log/apache2/error.log
        echo "Ban muon restart dich vu khong? Y/n ?"
                        read answer
                                if [ $answer = "y" -o $answer = "Y" ];
                                then
                                        echo "Khoi dong lai dich vu..."
                                        /etc/init.d/apache2 restart >/dev/null 2>&1
                                        echo "Khoi dong lai hoan tat, vui long kiem tra lai dich vu."
                                        sleep 5
                                        /usr/local/mbmenu/mbdomain
                                else
                                        echo "Quay lai menu chinh"
                                        sleep 3
                                        /usr/local/mbmenu/mbdomain
fi
fi

