#!/bin/bash
clear
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "- 1. Quan ly Domain : $(apache2 -v | cut -f3 -d' ' | head -1) - $(systemctl status apache2.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo "//---------------------------------------------------------------------//"
echo
echo "--//---------------------------------------------------------------------"
echo "1. Quan ly Domain > Danh sach Ten mien"
echo "-------------------------------------------------------------------------"
echo "/-----------------------------------------------------------------------/"
echo

listdomain="/usr/local/mbmenu/action/domain/listdomain"

echo "--------------Danh Sach Ten mien--------------"

cat $listdomain

echo "----------------------------------------------"

read -n 1 -s -r -p "An phim bat ky de quay lai - [CTRL+C] de thoat" $back
/usr/local/mbmenu/mbdomain
