#!/bin/bash
domain=$1
docroot="/mbwww/$domain"

cat > "/etc/apache2/mbwww.d.conf/$domain.conf" <<END
<VirtualHost *:80>
    ServerAdmin admin@$domain
    DocumentRoot "/mbwww/$domain/httpdocs"
    ServerName $domain
    ServerAlias www.$domain
    #errorDocument 404 /404.html
    ErrorLog "/mbwww/$domain/logs/$domain-error_log"
    CustomLog "/mbwww/$domain/logs/$domain-access_log" combined
    
    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>
    
    #PHP
    #<FilesMatch \.php$>
            #SetHandler "proxy:unix:/tmp/php-cgi-56.sock|fcgi://localhost"
    #</FilesMatch>
    
    #PATH
    <Directory "/mbwww/$domain/httpdocs">
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>
</VirtualHost>
<VirtualHost *:443>
    ServerAdmin admin@$domain
    DocumentRoot "/mbwww/$domain/httpdocs"
    ServerName $domain
    ServerAlias www.$domain
    #errorDocument 404 /404.html
    ErrorLog "/mbwww/$domain/logs/$domain-error_log"
    CustomLog "/mbwww/$domain/logs/$domain-access_log" combined
    
	#SSL
    SSLEngine On
    SSLCertificateFile $docroot/ssl/$domain.crt
    SSLCertificateKeyFile $docroot/ssl/$domain.key
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    SSLProtocol All -SSLv2 -SSLv3 -TLSv1
    SSLHonorCipherOrder On
	
    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>
    
    #PHP
    #<FilesMatch \.php$>
            #SetHandler "proxy:unix:/tmp/php-cgi-56.sock|fcgi://localhost"
    #</FilesMatch>
    
    #PATH
    <Directory "/mbwww/$domain/httpdocs">
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>
</VirtualHost>
END
