#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Xóa Backup Database"
echo "-------------------------------------------------------------------------"
echo ""
if [ ! "$(ls -A /usr/share/nginx/larvps/backup/db)" ]; then
    clear
    echo "Không có file backup database nào tồn tại."
    echo "Vui lòng uploads file backup database của bạn vào: /usr/share/nginx/larvps/backup/db"
    echo
    action_database
fi

i=1
for entry in `ls -At  /usr/share/nginx/larvps/backup/db`; do
    echo "$i) $entry"
    i=$((i+1));
done
echo "-------------------------------------------------------------------------"
echo "Tổng files: $((i-1))"
echo

read -p "Xóa toàn bộ backup database đang tồn tại trên VPS?:(y/n) " confirm

if [[ "$confirm" = "y" ]]; then
    rm -rf /usr/share/nginx/larvps/backup/db/*
    clear
    echo "Đã xóa toàn bộ files backup database."
    echo
    action_database
fi

read -p "Nhập file database bạn muốn xóa?: " file

if [[ $file ]]; then
    rm -rf /usr/share/nginx/larvps/backup/db/$file
    clear
    echo "Đã xóa file backup database."
    echo
    action_database
fi

action_database