#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Đổi Password"
echo "-------------------------------------------------------------------------"
echo ""
read -p "Nhập DB_User: " user


if [[ "$user" = "" ]]; then
    clear
    action_database
fi

if [ "$user" = "admin" ]; then
    clear
    echo "Tài khoản Admin không thể đổi Pass. Đây là tài khoản để script hoạt động."
    action_database
fi

read -p "Nhập DB_Password: " password
read -p "Xác nhận thay đổi password cho user $user? (y/n): " confirm

if [[ "$password" = "" ]]; then
    clear
    action_database
fi


if [[ "$confirm" = 'y' ]]; then
	echo "Đang tiến hành thay đổi password..."
	sleep 1
    mysql -u admin -p"$db_admin_password" -e "SET PASSWORD FOR '$user'@'localhost' = PASSWORD('$password')"
    clear
    echo "Đã thay đổi mật khẩu thành công"
    action_database
fi
action_database