#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "- 6. Quan ly database > Them database"
echo "/-----------------------------------------------------------------------/"
echo ""

read -p "1. Nhap DB_Name: " database
read -p "2. Nhap DB_User: " username
read -p "3. Nhap DB_Password: " password
read -p "Xac nhan them database? (y/n): " confirm

if [ "$database" = "" ] || [ "$username" = "" ] || [ "$password" = "" ]; then
    clear
    action_database
fi

if [[ "$confirm" = "y" ]]; then
	echo "Dang tien hanh them database moi..."
    # mysql -u admin -p"$db_admin_password" -e "show DATABASEs"
    mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $database"
    mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$username'@'localhost' IDENTIFIED BY '$password'"
    mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $database.* TO '$username'@'localhost'"
    mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"
    clear
    echo "Đã thêm databse thành công"
    echo
    echo "DB_Name: " $database
    echo "DB_User: " $username
    echo "DB_Password: " $password
    echo
    action_database
fi


