#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Xóa database"
echo "-------------------------------------------------------------------------"
echo ""

echo "Danh sách Database"
mysql -u admin -p"$db_admin_password" -e "show databases where \`database\` not in('information_schema', 'test', 'sys', 'phpmyadmin', 'mysql', 'performance_schema')"
echo

read -p "Nhập tên database bạn cần xóa: " database
read -p "Xác nhận xóa database? (y/n): " confirm

if [ "$database" = "" ]; then
    clear
    action_database
fi

if [[ "$confirm" = "y" ]]; then
	echo "Đang tiến hành xóa database..."
	sleep 1
    mysql -u admin -p"$db_admin_password" -e "DROP DATABASE $database"
    clear
    echo "Đã xóa database thành công."
    echo
    action_database
fi

action_database