#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "- 6. Quan ly Database > Import Database"
echo "/-----------------------------------------------------------------------/"
echo "Huong dan: Ban hay upload database (.sql hoặc .gz) vao thu muc /home/db"
echo

mkdir -p "/home/db"

selects=()
for entry in `ls -A /home/db | grep ".sql\|.gz"`; do
    selects+=("$entry")
done

PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}
do
	file=$select
	break
done

if [[ "$file" = "" ]]; then
	clear
	echo "Khong co file backup nao ton tai"
	echo "Ban hay upload database (.sql hoặc .gz) vao thu muc /home/db"
	sleep 3
	action_database
fi

path="/home/db/$file"
type="$(echo $path | grep ".gz")"

read -p "Ban co muon import $file vao database moi? (y/N): " confirm

if [[ "$confirm" = "y" ]]; then

	read -p "1. Nhap DB_Name: " database
	read -p "2. Nhap DB_User: " username
	read -p "3. Nhap DB_Password: " password

	if [ "$database" = "" ] || [ "$username" = "" ] || [ "$password" = "" ]; then
	    clear
	    action_database
	fi

	echo "Dang tien hanh tao database..."
	sleep 1
	mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $database"
	mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$username'@'localhost' IDENTIFIED BY '$password'"
	mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $database.* TO '$username'@'localhost'"
	mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"
	mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $database"
else
	mysql -u admin -p"$db_admin_password" -e "show databases where \`database\` not in('information_schema', 'test', 'sys', 'phpmyadmin', 'mysql', 'performance_schema')"
	read -p "Nhap ten Database co san ban muon them. 
Du lieu cua Database do se bi xoa: " database

	if [[ "$database" = "" || "$database" = "0" ]]; then
		action_database
	fi

	mysql -u admin -p"$db_admin_password" -e "DROP DATABASE $database"
	mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $database"
fi

sleep 2
echo "Dang tien hanh Import database..."
echo "Vui long doi..."
echo
if [[ "$type" ]]; then
zcat $path | mysql -u admin -p"$db_admin_password" $database
else
mysql -h localhost -u admin -p"$db_admin_password" $database < $path
fi
sleep 2
clear
echo "Hoan thanh."
echo "Thong tin database:"
echo "phpMyAdmin: http://$(hostname -I | cut -f1 -d' '):$port_admin/phpmyadmin"
echo "Database: $database"
if [[ "$username" && "$password" ]]; then
	echo "Username: $username"
	echo "Password: $password"
fi
echo
action_database