#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Xem thông tin Database"
echo "-------------------------------------------------------------------------"
echo
echo "Danh sách Database"
mysql -u admin -p"$db_admin_password" -e "show databases where \`database\` not in('information_schema', 'test', 'sys', 'phpmyadmin', 'mysql', 'performance_schema')"
echo
read -p "Nhập tên database bạn muốn xem thông tin: " database

if [ "$database" = '' ]; then
    clear
    action_database
fi
echo "Thông tin database: $database:"
echo
mysql -u admin -p"$db_admin_password" -e "SELECT * FROM mysql.db WHERE Db = '$database'\G"
echo
action_database