#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Restore Database"
echo "-------------------------------------------------------------------------"
echo "Dung lượng files: $( du -hs '/usr/share/nginx/larvps/backup/db' )"
echo "-------------------------------------------------------------------------"
echo
if [ ! "$(ls -A /usr/share/nginx/larvps/backup/db)" ]; then
	clear
	echo "Không có file backup nào tồn tại."
	echo "Vui lòng uploads file backup của bạn vào: /usr/share/nginx/larvps/backup/db"
	echo
	action_database
fi

i=1
for entry in `ls -At  /usr/share/nginx/larvps/backup/db`; do
    echo "$i) $entry"
    i=$((i+1));
done
echo "-------------------------------------------------------------------------"
echo "Tổng files: $((i-1))"
echo

read -p "Nhập file bạn muốn phục hồi: " file

if [[ ! -f /usr/share/nginx/larvps/backup/db/$file ]]; then
	echo "File backup không tồn tại";
    action_backup_restore
fi

db_url=$(ls -A /usr/share/nginx/larvps/backup/db/$file)
if [[ ! $db_url ]]; then
	echo "Không tồn tại backup database";
	action_database
fi

db_name=$(echo  $file | cut -f2 -d'.')
db_user=$(echo $db_name | sed 's/_db/_user/' )
db_password=$(< /dev/urandom tr -dc a-z0-9 | head -c${1:-24};echo;)

mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $db_name"
mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"

#tien hanh restore db
zcat $db_url | mysql -u admin -p"$db_admin_password" $db_name
clear
echo "Đã restore database $db_name"
echo
echo "Danh sách Database"
mysql -u admin -p"$db_admin_password" -e "show databases where \`database\` not in('information_schema', 'test', 'sys', 'phpmyadmin', 'mysql', 'performance_schema')"
echo
echo
action_database