#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "11. Quan ly Utility > Cai dat composer"
echo "/-----------------------------------------------------------------------/"

if [[ ! -f /usr/local/bin/composer ]]; then
    echo "Đang tiến hành cài đặt Composer..."
    sleep 1
    cd

    if [[ ! -f /var/swap.1 ]]; then
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1
    fi
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -d memory_limit=-1 composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer
clear
echo "Đã cài đặt Composer thành công"
echo
action_utility
else
    clear
    echo "Composer đã được cài đặt"
    echo
    action_utility
fi