#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "11. Quan ly Utility > iFrame"
echo "/-----------------------------------------------------------------------/"

if [[ `cat /etc/nginx/nginx.conf | grep "#add_header X-Frame"` ]]; then
echo "iFrame: InActive"

read -p "Ban co muon bat iFrame? (y/n): " confirm
if [[ "$confirm" = "y" ]]; then
sed -i "s/#add_header X-Frame/\add_header X-Frame/g" /etc/nginx/nginx.conf
nginx -t && service nginx restart
clear
echo "Da bat iFrame"
action_utility
fi


else
echo "iFrame: Active"

read -p "Ban co muon tat iFrame? (y/n): " confirm
if [[ "$confirm" = "y" ]]; then
sed -i "s/add_header X-Frame/\#add_header X-Frame/g" /etc/nginx/nginx.conf
nginx -t && service nginx restart
clear
echo "Da tat iFrame"
action_utility
fi

fi

action_utility