#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Cấu hình Laravel - Public"
echo "-------------------------------------------------------------------------"
echo ""

read -p "Nhập domain của bạn: " domain
read -p "Xác nhận Public hoặc khôi phục gốc (c/x): " confirm_lp

# kiem tra ton tai
username=${domain//[-._]/}
path="/home/$username/$domain"
if [[ ! -d "$path" ]]; then
    clear
    echo "Domain không tồn tại trên VPS."
    echo
    action_utility
fi

if [[ "$confirm_lp" == 'c' ]]; then
    sed -i "s/$domain\/public_html;/$domain\/public_html\/public;/g" /etc/nginx/conf.d/$domain.conf
    systemctl restart nginx.service
    clear
    echo "Đã cấu hình Laravel - Public thành công"
    echo 
    action_utility
fi

if [[ "$confirm_lp" == 'x' ]]; then
    sed -i "s/$domain\/public_html\/public;/$domain\/public_html;/g" /etc/nginx/conf.d/$domain.conf
    systemctl restart nginx.service
    clear
    echo "Đã khôi phục gốc thành công thành công"
    echo 
    action_utility
fi

clear
action_utility