#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions


domain=$1
username=${domain//[-._]/}
password=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
sleep 1
password_auth=$(date +%s | sha256sum | base64 | head -c 24 ; echo)
db_name=$2
db_user=$3
db_password=$4

# Tạo user và đổi pass
useradd $username

# pass ftp
change_pass=$(expect -c "
spawn passwd $username
expect \"New password\"
send \"$password\r\"
expect \"Retype new password\"
send \"$password\r\"
expect eof
")
echo $change_pass

## pass http auth
ass_secure=$(expect -c "
spawn htpasswd /usr/share/nginx/larvps/passwd/.htpasswd $username
expect \"New password\"
send \"$password_auth\r\"
expect \"Retype new password\"
send \"$password_auth\r\"
expect eof
")
echo $pass_secure


#Tạo thư mục quản lý web
mkdir -p /home/$username/$domain/public_html
mkdir -p /home/$username/$domain/logs
mkdir -p /home/$username/$domain/tmp
mkdir -p /home/$username/$domain/ssl
mkdir -p /home/$username/$domain/session
mkdir -p /home/$username/$domain/restore


chmod 755 /home/$username
chmod 755 /home/$username/$domain/public_html
chmod 700 /home/$username/$domain/logs
chmod 700 /home/$username/$domain/tmp
chmod 700 /home/$username/$domain/ssl
chmod 700 /home/$username/$domain/session
chmod 700 /home/$username/$domain/restore

# chown
chown root:root /home/$username
chown -hR $username:$username /home/$username/$domain/

# add group
usermod -G sftp_users $username

cat > "/home/$username/$domain/public_html/index.html" <<END
<h1>Ban da cai dat LarVPS thanh cong.</h1>
END

chcon -R -t httpd_sys_content_t /home/$username/$domain/public_html
chcon -R -t httpd_sys_rw_content_t /home/$username/$domain/public_html

for (( n = 9001; n <= 9500; n++ )); do
    x=$(grep -rnw '/etc/php-fpm.d/' -e $n >> /dev/null 2>&1 && echo 1)
    if [[ ! $x ]]; then
       port_listen=$n
       break
    fi
done


cat > "/etc/php-fpm.d/$domain.conf" <<END
[$domain]
listen = 127.0.0.1:$port_listen
user = $username
group = $username
listen.mode = 644
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 5
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 4
pm.max_requests = 500
request_terminate_timeout = 300
php_admin_value[open_basedir] = /home/$username/$domain/
php_admin_value[upload_tmp_dir] = /home/$username/$domain/tmp
php_admin_value[session.safe_path] = /home/$username/$domain/session
php_admin_value[error_log] = /home/$username/$domain/logs/php_error_log
END


# cấu hình nginx
cat > "/etc/nginx/conf.d/$domain.conf" <<END
server {
    listen 80;
    server_name www.$domain;
    return \$scheme://$domain\$request_uri;
}

server {
    listen 80;
    server_name $domain;
    charset utf-8;

    #access_log off;
    #include /etc/nginx/rocket-nginx/default.conf;
    #access_log /home/$username/$domain/logs/access.log;
    #error_log off;
    error_log /home/$username/$domain/logs/error.log;
    root /home/$username/$domain/public_html;
    index index.php index.html index.htm;
    
    # Custom configuration
    include /home/$username/$domain/public_html/*.conf;
    include /etc/larvps/custom_nginx/*.conf;

    rewrite ^/sitemap_index.xml\$ /index.php?sitemap=1 last;
    rewrite ^/([^/]+?)-sitemap([0-9]+)?.xml\$ /index.php?sitemap=\$1&sitemap_n=\$2 last;

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options nosniff;
    add_header X-Download-Options noopen;
    add_header X-Powered-By LarVPS;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    autoindex off;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        try_files \$uri =404;
        fastcgi_intercept_errors on;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 8 16k;
        fastcgi_busy_buffers_size 32k;
        fastcgi_temp_file_write_size 32k;
        fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass  127.0.0.1:$port_listen;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml|svg|woff2|woff)$ {
        access_log        off;
        log_not_found     off;
        expires           365d;
    }

    location ~* \.(txt|js|css)$ {
        access_log off;
        expires 365d;
        log_not_found off;
        break;
    }

    location = /favicon.ico {
      access_log     off;
      log_not_found  off;
    }

    location = /robots.txt {
      access_log     off;
      log_not_found  off;
    }

    location ~ /\. {
        access_log off;
        log_not_found off; 
        deny all;
    }
    
    location ~ \.htaccess {
        deny all;
    }

    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    location = /wp-config.php {
        deny all;
        return 444;
    }

    location = /xmlrpc.php {
        deny all;
        access_log off;
        log_not_found off;
        return 444;
    }

    location ~* /(?:uploads|files|wp-content|wp-includes|akismet)/.*.php\$ {
        deny all;
        access_log off;
        log_not_found off;
        return 444;
    }

    location ~* /wp-includes/.*.php$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ /\.(svn|git)/* {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ /\.ht {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ /\.user.ini { 
        deny all; 
        access_log off;
        log_not_found off;
    }
    
}
END

# set chown
chown -R $username:$username /home/$username/$domain/public_html

mysql -u admin -p"$db_admin_password" -e "DROP DATABASE IF EXISTS $db_name"
mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $db_name"
mysql -u admin -p"$db_admin_password" -e "DROP USER IF EXISTS '$db_user'@'localhost'"
mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$db_user'@'localhost' IDENTIFIED BY '$db_password'"
mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_user'@'localhost'"
mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"


# lưu config user
cat > "/etc/larvps/user/.$domain.conf" <<END
[$domain]
username=$username
password=$password_auth
password_sftp=$password
domain=$domain
db_name=$db_name
db_user=$db_user
db_password=$db_password
phpMyAdmin=http://$ip:$port_admin/phpmyadmin
public_html=/home/$username/$domain/public_html
END

systemctl restart nginx.service
systemctl restart php-fpm.service

clear
echo
echo "Cam on ban da su dung LarVPS"
echo "Ban da them domain thanh cong. Hay luu lai thong tin de su dung ve sau"
echo "-------------------------------------------------------------------------"
echo "1.  Domain                : $domain"
echo "2.  DB_Name               : $db_name"
echo "3.  DB_User               : $db_user"
echo "4.  DB_Password           : $db_password"
echo "6.  PhpMyAdmin            : http://$ip:$port_admin/phpmyadmin"
echo "7.  Username              : $username"
echo "8.  Password_Auth         : $password_auth"
echo "9.  Password_SFTP         : $password"
echo "10. SFTP Host             : $ip"
echo "11. SFTP Port             : $port_ssh"
echo "12. Upload source         : /home/$username/$domain/public_html"
echo "-------------------------------------------------------------------------"
echo

