#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "19. Quan ly Image > Danh sach domain"
echo "/-----------------------------------------------------------------------/"
echo

choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_image_manager
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_image_manager
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_image_manager
fi
username=${domain//[-._]/}

if [[ ! -f '/usr/bin/pngquant' ]] || [[ ! -f '/usr/bin/jpegoptim' ]]; then
yum -y install jpegoptim pngquant
clear
fi

read -p "Ma nguon web ban la Wordpress? (y/N): " confirm_wp

if [[ "$confirm_wp" = "y" ]]; then
path=/home/$username/$domain/public_html/wp-content/uploads
else
echo "Vidu: /home/$username/$domain/public_html/"
read -p "Nhap duong dan thu muc hinh anh cua ban: " path  
fi

if [[ ! -d $path ]]; then
    clear
    echo "Duong dan $path khong ton tai"
    action_image_manager
fi

before_optimize=$(du -hs $path)
echo "Dung luong thu muc hinh anh: $( du -hs $path )"

echo "Vui long backup lai du lieu hinh anh truoc khi Optimize Images."
read -p "Tien hanh toi uu hinh anh (y/N):" confirm

if [[ "$confirm" = "y" ]]; then
# tar fcvz "/home/$username/$domain/public_html/bk_images.tar.gz" --absolute-names "$path"
clear
# echo "Thu muc uploads truoc khi toi uu se dc backup tai:"
# echo "/home/$username/$domain/public_html/bk_images.tar.gz"
# echo "Ban co the xoa hoac phuc hoi lai neu muon"
sleep 3
echo "Dang tien hanh toi uu..."
find $path -type f -name "*.jpg" -exec jpegoptim --strip-all -m76 {} \;
find $path -type f -name "*.png" -exec pngquant --force --quality=85-100 --skip-if-larger --strip --verbose \{} --output \{} \;
chown -hR $username:$username /home/$username/$domain/public_html
chmod -R a=r,u+w,a+X /home/$username/$domain/public_html
clear
echo "Da toi uu thanh cong"
echo "/-----------------------------------------------------------------------/"
echo "Truoc: $before_optimize"
echo "Sau: $( du -hs $path )"
echo "/-----------------------------------------------------------------------/"
fi
sleep 3
action_image_manager

