#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "Thay doi phien ban PHP - Hien tai: v$(php -v | head -n 1 | cut -d " " -f 2)"
echo "/-----------------------------------------------------------------------/"
echo
PS3='
Nhap lua chon (1-3) [0=Thoat]: '
options=("7.4" "7.3" "7.2")

select opt in "${options[@]}"
do
    case $opt in
        "7.4")
            '/etc/larvps/menu/action/php_manager/php74'
            ;;
        "7.3")
            '/etc/larvps/menu/action/php_manager/php73'
            ;;
        "7.2")
            '/etc/larvps/menu/action/php_manager/php72'
            ;;
        *) action_php_manager;;
    esac
done
