#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "6. Quan ly PHP > PHP 7.2"
echo "/-------------------------------------------------------------------------/"
echo
current=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
if [[ "$current" = '7.2' ]]; then
	clear
	echo "Bạn đang sử dụng PHP 7.2. Vui lòng chọn phiên bản khác"
	echo
	action_php_manager
fi

read -p "Xác nhận chuyển sang PHP 7.2 cho VPS? (y/n): " confirm

if [[ "$confirm" = "y" ]]; then
	echo "Đã tiến hành chuyển sang php 7.2..."
	sleep 1
	dnf install yum-utils http://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
	dnf module reset php -y
	dnf module enable php:remi-7.2 -y
	dnf module install php:remi-7.2 -y --allowerasing
	dnf install -y gd php-pear php-devel gcc
	dnf install -y php-opcache php-fpm php-dom php-simplexml php-ssh2 php-xml php-xmlreader php-curl php-date php-exif php-filter php-ftp php-gd php-hash php-iconv php-json php-libxml php-pecl-imagick php-mbstring php-mysqlnd php-openssl php-pcre php-posix php-sockets php-spl php-tokenizer php-zlib

	systemctl enable php-fpm.service
	systemctl restart php-fpm.service
	clear
	echo "VPS đã chuyển sang sử dụng php 7.2"
	echo "Thông tin:"
	php -v
	echo
	action_php_manager
fi
action_php_manager