#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Tuy chinh php.ini"
echo "-------------------------------------------------------------------------"
echo ""
echo "Huon dan:"
echo "- Ctrl + O chọn Y: De luu lai cau hinh thay doi."
echo "- Khoi dong lai php-fpm sau khi thay doi: larvps php -r"
echo "- Dang chuan bi mo PHP.ini..."
sleep 5
nano /etc/php.d/00-larvps-custom.ini