#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

if [ "$EUID" -ne 0 ]; then 
  echo "Dang chuyen sang Root"
  sudo -i
  sleep 3
fi

one=$( [ "$1" != "" ] && echo $1 || echo "" )
two=$( [ "$2" != "" ] && echo $2 || echo "" )
three=$( [ "$3" != "" ] && echo $3 || echo "" )
four=$( [ "$4" != "" ] && echo $4 || echo "" )
five=$( [ "$5" != "" ] && echo $5 || echo "" )
six=$( [ "$6" != "" ] && echo $6 || echo "" )


if [[ "$one" = "" ]]; then
	echo "Vui long nhap hanh dong. Vi du: list domain"
fi

if [ "$one" = "domain" ]; then
   "/etc/larvps/menu/action/domain/list"
   exit 1
fi

if [ "$one" = "ssl" ]; then
   certbot certificates | grep -Ev "Private|Certificate|Serial|Found"
   exit 1
fi

