#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//-----------------------------------------------------------------------"
echo "9. Quan ly Application > Cai dat Laravel"
echo "-------------------------------------------------------------------------"
echo ""
choose_domain

if [ "$domain" = '' ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_application
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_application
fi

read -p "Xác nhận cài đặt Laravel cho $domain (y/n): " confirm

c_db_name=$(< /dev/urandom tr -dc a-z | head -c${1:-8};echo;)
db_name=${c_db_name}_db
db_user=${c_db_name}_user
db_password=$(< /dev/urandom tr -dc a-z0-9 | head -c${1:-24};echo;)

username=${domain//[-._]/}

# kiem tra ton tai
# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain không tồn tại trên VPS."
    echo
    action_application
fi

if [[ "$confirm" = "y" ]]; then
        sleep 1
        if [[ ! -f "/usr/local/bin/composer" ]]; then
            echo "Đang cài đặt Composer..."
            sleep 1

if [[ ! -f /var/swap.1 ]]; then
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1
fi
            cd
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -d memory_limit=-1 composer-setup.php
            php -r "unlink('composer-setup.php');"
            mv composer.phar /usr/local/bin/composer
            clear
        fi

        # lam sach
        echo "Đang tiến hành cài đặt Laravel phiên bản mới nhất ...."
        sleep 1
        rm -rf /home/$username/$domain/public_html/*
        cd /home/$username/$domain/public_html/
        composer create-project --prefer-dist laravel/laravel ./

        # set chown
        chown -R $username:$username /home/$username/$domain/public_html
        chmod -R a=r,u+w,a+X /home/$username/$domain/public_html

        # create db
        mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $db_name"
        mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$db_user'@'localhost' IDENTIFIED BY '$db_password'"
        mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_user'@'localhost'"
        mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"

        # set db
        sed -i "s/APP_ENV=local/APP_ENV=production/g" /home/$username/$domain/public_html/.env
        sed -i "s/DB_DATABASE=laravel/DB_DATABASE=$db_name/g" /home/$username/$domain/public_html/.env
        sed -i "s/DB_USERNAME=root/DB_USERNAME=$db_user/g" /home/$username/$domain/public_html/.env
        sed -i "s/DB_PASSWORD=/DB_PASSWORD=$db_password/g" /home/$username/$domain/public_html/.env

        # tro public
        sed -i "s/$domain\/public_html;/$domain\/public_html\/public;/g" /etc/nginx/conf.d/$domain.conf
        service nginx restart

        clear
        echo "-------------------------------------------------------------------------"
        echo "Cám ơn bạn đã sử dụng LarVPS."
        echo "Bạn đã cài đặt Laravel thành công. Hãy lưu lại thông tin để sử dụng về sau"
        echo "-------------------------------------------------------------------------"
        echo "1. Domain            : http://$domain"
        echo "2. DB_Name           : $db_name"
        echo "3. DB_User           : $db_user"
        echo "4. DB_Password       : $db_password"
        echo "-------------------------------------------------------------------------"
        echo
        action_application

fi