#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "9. Quan ly Application > Cai dat Wordpress"
echo "-------------------------------------------------------------------------"
echo ""
choose_domain

db_name=""
db_user=""
db_password=""

if [ "$domain" = '' ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_application
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_application
fi

read -p "Xác nhận cài đặt Wordpress phiên bản mới nhất cho domain $domain. (y/n): " confirm


username=${domain//[-._]/}
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain không tồn tại trên VPS."
    echo
    action_application
fi

c_db_name=$(< /dev/urandom tr -dc a-z | head -c${1:-8};echo;)
db_name=${c_db_name}_db
db_user=${c_db_name}_user
db_password=$(< /dev/urandom tr -dc a-z0-9 | head -c${1:-24};echo;)
prefix=$(< /dev/urandom tr -dc a-z | head -c${1:-6};echo;)


if [[ "$confirm" = "y" ]]; then
        echo "Đang thiết lập cài đặt Wordpress cho $domain..."
        sleep 1
        # lam sach
        rm -rf /home/$username/$domain/public_html/*

        # create db
        mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $db_name"
        mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$db_user'@'localhost' IDENTIFIED BY '$db_password'"
        mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_user'@'localhost'"
        mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"
        
        cd
        curl -O https://wordpress.org/latest.tar.gz
        tar -zxvf latest.tar.gz
        cd wordpress
        cp -rf . /home/$username/$domain/public_html
        cd ..
        rm -rf wordpress
        rm -rf latest.tar.gz

        cd /home/$username/$domain/public_html

        #set WP salts
        SALT=$(curl -L https://api.wordpress.org/secret-key/1.1/salt/)

cat > "/home/$username/$domain/public_html/wp-config.php" <<END
<?php
define('DISALLOW_FILE_EDIT', true);
define( 'WP_MEMORY_LIMIT', '128M' );
define( 'WP_CACHE', true );
define('FS_METHOD', 'direct');
define( 'DB_NAME', '$db_name' );
define( 'DB_USER', '$db_user' );
define( 'DB_PASSWORD', '$db_password' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );
define('DISABLE_WP_CRON', false);

$SALT

\$table_prefix = "${prefix}_";

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', dirname( __FILE__ ) . '/' );
}
require_once( ABSPATH . 'wp-settings.php' );

END

#create robots
cat > "/home/$username/$domain/public_html/robots.txt" <<END
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
END

# set chown
chown -R $username:$username /home/$username/$domain/public_html
chmod 0400 /home/$username/$domain/public_html/wp-config.php
rm -rf /home/$username/$domain/public_html/readme.html
rm -rf /home/$username/$domain/public_html/license.txt

clear
echo "-------------------------------------------------------------------------"
echo "Cám ơn bạn đã sử dụng LarVPS."
echo "Bạn đã cài đặt Wordpress thành công. Hãy lưu lại thông tin để sử dụng về sau"
echo "-------------------------------------------------------------------------"
echo "1. Domain            : http://$domain"
echo "2. DB_Name           : $db_name"
echo "3. DB_User           : $db_user"
echo "4. DB_Password       : $db_password"
echo "-------------------------------------------------------------------------"
echo
action_application
fi