#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "16. Quan ly Disk > tmp"
echo "/-----------------------------------------------------------------------/"
echo
cd /tmp && du -sh */
echo "-------------------------------------------------------------------------"
echo "Tong: $(du -sh /tmp)"
sleep 3
action_disk_manager