#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "16. Quan ly Disk > usr"
echo "/-----------------------------------------------------------------------/"
echo
cd /usr && du -sh */
echo "-------------------------------------------------------------------------"
echo "Tong: $(du -sh /usr)"
sleep 3
action_disk_manager