#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "16. Quan ly Disk > Root"
echo "/-----------------------------------------------------------------------/"
echo
cd && du --exclude=/proc -sh /*
echo "-------------------------------------------------------------------------"
echo "Tong: $(du --exclude=/proc -sh /)"
sleep 3
action_disk_manager