#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "16. Quan ly Disk > Tim file lon trong domain"
echo "/-----------------------------------------------------------------------/"
echo ""

choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_ssl_manager
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_ssl_manager
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    action_ssl_manager
fi
username=${domain//[-._]/}

path="/home/$username/$domain"
find $path -not -path "/proc/*" -type f -exec du -Sh {} + | sort -rh | head -n 10
sleep 3
action_disk_manager