#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "//---------------------------------------------------------------------//"
echo "Canh bao FullDisk"
echo "-------------------------------------------------------------------------"
echo "Filesystem     Type       Size Used  Avail Use% Mounted on"
echo "$(df -T -h | grep "sd")"
echo "-------------------------------------------------------------------------"
echo "Canh bao khi con: $limit_disk (GB)"
echo "/-----------------------------------------------------------------------/"
echo 
read -p "Nhap so GB ban muon canh bao [Nhap 1-10]: " limit

if [[ "$limit" = "" ]] || [[ "$limit" = "0" ]] ; then
	action_disk_manager
fi

re='^[0-9]+$'
if ! [[ $limit =~ $re ]] ; then
    clear
    echo "Vui long nhap so tu 1-10."
    action_disk_manager
fi

sed -i "/limit_disk=/d" /etc/larvps/.larvps.conf
echo "limit_disk=$limit" >> /etc/larvps/.larvps.conf
clear
echo "Hoan thanh."
action_disk_manager