#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Clean WP Rocket (Cache + Preload)"
echo "/-----------------------------------------------------------------------/"
echo

get_choose_domain
path_clear_wp="${path}/rocket-clean.php"
cat > "$path_clear_wp" << END
<?php 
require( 'wp-load.php' );
if ( function_exists( 'rocket_clean_domain' ) ) {
	rocket_clean_domain();
}
if ( function_exists( 'run_rocket_sitemap_preload' ) ) {
	run_rocket_sitemap_preload();
}
echo "Hoan tat"
END
echo "Dang tien hanh clean cache và preload"
curl "http://$domain/rocket-clean.php"
chown $username:$username $path_clear_wp
rm -f $path_clear_wp
clear
echo "Hoan thanh"
action_wp_manager