#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Clear Cache All"
echo "/-----------------------------------------------------------------------/"
echo

if [ "$(ls -At /etc/larvps/user)" ]; then
	i=1
	for entry in `ls -A /etc/larvps/user`; do
	    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
	    username=${domain//[-._]/}
	    path="/home/$username/$domain/public_html/"
	    cd $path
	    wp cache flush --allow-root
	    wp rewrite flush --allow-root
	    larvps chmod $domain
	done
fi
action_wp_manager
