#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Clear Cache"
echo "/-----------------------------------------------------------------------/"
echo

get_choose_domain

cd $path
wp cache flush --allow-root
wp rewrite flush --allow-root
larvps chmod $domain
action_wp_manager
