#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Unused Inactive Theme - Plugin"
echo "/-----------------------------------------------------------------------/"
echo

get_choose_domain
echo
wp --path=$path theme list --status=inactive --allow-root
echo
read -p "Xac nhan xoa cac Theme khong su dung (unsed_inactive): (y/N) " confirm_remove_theme

if [[ "$confirm_remove_theme" = "y" ]]; then
    echo "Dang tien hanh xoa Theme"
    for entry in `wp --path=$path theme list --status=inactive --field=name --allow-root | xargs`; do
       wp theme delete ${entry} --path=$path --allow-root
    done
    wp cache flush --path=$path --allow-root
    clear
    echo "Da hoan thanh xoa theme."
fi

echo
wp --path=$path plugin list --status=inactive --allow-root
echo
read -p "Xac nhan xoa cac Plugin khong su dung (unsed_inactive): (y/N) " confirm_remove_plugin

if [[ "$confirm_remove_plugin" = "y" ]]; then
    echo "Dang tien hanh xoa Plugin"
    for entry in `wp --path=$path plugin list --status=inactive --field=name --allow-root | xargs`; do
       wp plugin delete ${entry}  --path=$path --allow-root
    done
    wp cache flush --path=$path --allow-root
    clear
    echo "Da hoan thanh xoa plugin."
fi
action_wp_manager