#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Disable File Mods + File Edit"
echo "/-----------------------------------------------------------------------/"
echo

get_choose_domain

path_wp_config=$path'wp-config.php';
new_path_wp_config="/home/$username/$domain/wp-config.php"

clear

if [[ -f $path_wp_config ]]; then
path_wp_config=$path_wp_config
else
	if [[ -f $new_path_wp_config ]]; then
path_wp_config=$new_path_wp_config
	else
	echo "Khong tim thay wp-config.php"
	action_wp_manager
	fi
fi

#delete
sed -i "/DISALLOW_FILE_EDIT/d" $path_wp_config
sed -i "/DISALLOW_FILE_MODS/d" $path_wp_config

# # tiến hành edit
sed -i "/<?php/a define( 'DISALLOW_FILE_EDIT', true);" $path_wp_config
sed -i "/<?php/a define( 'DISALLOW_FILE_MODS', true);" $path_wp_config

echo "Da Disable File Mods + File Edit thong cong cho domain $domain"

action_wp_manager
