#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Ho tro Webp"
echo "/-----------------------------------------------------------------------/"
echo

get_choose_domain

if [[ -f "$path/nginx-webp.conf" ]]; then
read -p "Domain da cau hinh Webp. Ban co muon xoa? (y/n) " confirm
rm -f "$path/nginx-webp.conf"
echo "Da xoa Webp cua $domain"

else

cat > "$path/nginx-webp.conf" <<END
location ~* ^.+\.(png|jpe?g)\$ {
  add_header Vary Accept;
  try_files $uri\$webp_suffix \$uri =404;
}
END
nginx -t && service nginx restart
echo "Da thiet lap Webp cho $domain"

fi


action_wp_manager