#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Update theme"
echo "/-----------------------------------------------------------------------/"
echo

get_choose_domain

echo
echo "Dang tien hanh cap nhat themes cho $domain"
wp theme update --all --path=$path --allow-root
wp cache flush --path=$path --allow-root
wp rewrite flush --path=$path --allow-root
larvps chmod $domain
echo
action_wp_manager

