#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "18. Quan ly Wordpress > Update Wordpress Core"
echo "/-----------------------------------------------------------------------/"
echo

echo "Phien ban Wordpress: "
echo "/-----------------------------------------------------------------------/"
for entry in `ls -A /etc/larvps/user`; do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    if [ "$domain" != "${domain/.}" ]; then
    	username=${domain//[-._]/}
    	path="/home/$username/$domain/public_html/"
        echo "${domain} - v$(wp core version --path=$path --allow-root)"
    fi
done
echo "/-----------------------------------------------------------------------/"
echo
get_choose_domain

echo
echo "Dang tien hanh cap nhat Wp cho $domain"
wp core update --path=$path --allow-root
wp core update-db --path=$path --allow-root
wp cache flush --path=$path --allow-root
wp rewrite flush --path=$path --allow-root
larvps chmod $domain
echo
action_wp_manager
