#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "8. Quan ly Fail2ban > Khoa IP"
echo "/-----------------------------------------------------------------------/"
echo ""
read -p "Nhap Ip ban muon khoa: " ip
fail2ban-client set sshd banip $ip
fail2ban-client set nginx-http-auth banip $ip

echo "Dang tien hanh khoa IP $ip ..."
sleep 1
clear
echo "Da khoa IP $ip."
action_fail2ban