#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "8. Quan ly Fail2ban > Mo khoa IP"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-15-48"
echo "/-----------------------------------------------------------------------/"
echo 
read -p "Nhap Ip ban muon mo khoa: " ip
fail2ban-client set sshd unbanip $ip
fail2ban-client set nginx-http-auth unbanip $ip

echo "Dang tien hanh mo khoa IP $ip ..."
sleep 1
clear
echo "Da mo khoa IP $ip."
action_fail2ban
