#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "8. Quan ly Fail2ban > Danh sach IP da mo khoa"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-15-46"
echo "/-----------------------------------------------------------------------/"
echo 
zgrep -h "Restore " /var/log/fail2ban.log* | awk '{print $NF}' | sort | uniq -c
action_fail2ban