#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Thêm cấu hình nginx cho domain.conf"
echo "-------------------------------------------------------------------------"
echo 

choose_domain

if [ "$domain" = "" ]; then
    clear
    echo "Bạn chưa nhập Domain."
    echo
    action_lets_encrypt
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain bạn nhập không đúng định dạng."
    echo
    action_lets_encrypt
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ ! -f "$path" ]]; then
    clear
    echo "Domain không tồn tại trên VPS."
    echo
    action_lets_encrypt
fi


echo "Hướng dẫn:"
echo "- Sau khi thay đổi gõ larvps nginx -r để khởi động lại Nginx"
echo "- Ctrl + X hoặc Ctrl + 0 chọn Y: Để lưu lại thay đổi cấu hình."
echo
echo "Đang chuẩn bị mở cấu hình cho $domain.conf..."
sleep 4

username=${domain//[-._]/}

if [[ ! -f "/home/$username/$domain/public_html/nginx-$domain.conf" ]]; then
 	touch /home/$username/$domain/public_html/nginx-$domain.conf
	echo "Đã tạo file cấu hình $domain.conf tại /home/$username/$domain/public_html/nginx-$domain.conf"
	sleep 2
fi 

nano /home/$username/$domain/public_html/nginx-$domain.conf
