#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "-------------------------------------------------------------------------"
echo "Thêm cấu hình cho nginx.conf"
echo "-------------------------------------------------------------------------"
echo ""
echo "Hướng dẫn:"
echo "- Sau khi thay đổi gõ larvps nginx -r để khởi động lại Nginx"
echo "- Ctrl + X hoặc Ctrl + 0 chọn Y: Để lưu lại thay đổi cấu hình."
echo
echo "Đang chuẩn bị mở cấu hình cho nginx.conf..."
sleep 4
nano /etc/larvps/nginx/global.conf