#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "3. Quan ly SSH/SFTP > Thay doi port SSH"
echo "-------------------------------------------------------------------------"
port_open=$(cat /etc/ssh/sshd_config | grep "Port " | cut -f2 -d" ")
echo "Port SSH hien tai: $port_open"
echo "/-----------------------------------------------------------------------/"
echo ""

read -p "Nhap Port SSH moi [2000-9999]: " port_new

if [ "$port_new" = '' ]; then
    clear
    echo "Ban chua nhap Port."
    echo
    action_ssh
fi

if [[ ! $port_new =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Port nhap khong dung dinh dang"
    echo
    action_ssh
fi


if [ "$port_new" != "$port_open" ] && [ "$port_new" != "$port_admin" ]; then
	read -p "Xac nhan thay doi port SSH? (y/n): " confirm

	if [ "$confirm" = "y" ]; then
	   	echo "Dang tien hanh thay doi port SSH..."
	   	echo ""
	   	sleep 1

	   	sed -i "/Port/d" /etc/ssh/sshd_config
		sed -i "/ListenAddress ::/a Port $port_new" /etc/ssh/sshd_config

	   	# sed -i "s/#Port $port_open/Port $port_new/g" /etc/ssh/sshd_config
	    # sed -i "s/Port $port_open/Port $port_new/g" /etc/ssh/sshd_config

	    firewall-cmd --zone=public --remove-port=$port_open/tcp
	    semanage port -a -t ssh_port_t -p tcp $port_new
	    systemctl reload sshd.service
	    firewall-cmd --permanent --zone=public --add-port=$port_new/tcp
	    firewall-cmd --reload
	  
	    #fail2ban
	    sed -i "/port/d" /etc/fail2ban/jail.d/sshd.local
	    echo "port=$port_new" >> /etc/fail2ban/jail.d/sshd.local
	    fail2ban-client reload
	    
	    echo "Da thay doi port $port_new thanh cong"
	    echo "ssh -p $port_new root@$(hostname -I | cut -f1 -d' ')"
	    echo ""
	    action_ssh
	else
		clear
		echo
		action_ssh
	fi

else
	clear
	echo "Vui long su dung port SSH khac."
	echo
	action_ssh
fi

