#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "3. Quan ly SSH/SFTP > Thay doi sFTP Password User"
echo "/-----------------------------------------------------------------------/"
echo ""

choose_user
passwd $username
sleep 3

domain=${find_domain $username}

sed -i "/password_sftp=/d" /etc/larvps/user/.${domain}.conf
echo "password_sftp=$password" >> /etc/larvps/user/.${domain}.conf

clear
echo "Hoan thanh."
action_ssh
