#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "3. Quan ly SSH/SFTP > Thay doi SSH/sFTP Password User Root"
echo "/-----------------------------------------------------------------------/"
echo ""

passwd
sleep 3
clear
echo "Hoan thanh."


action_ssh
