#!/bin/bash
listdomain="/usr/local/mbmenu/action/domain/listdomain"

clear
if [ -z "$domain" ]; then
cat $listdomain
read -p "Nhap domain can tao FTP trong danh sach tren may chu [5=Quay lai]: " domain
fi

if [ "$domain" = "5" ];
then
echo "Quay lai menu chinh..."
sleep 5
/usr/local/mbmenu/mbftp
fi

if [ "$domain" = '' ];
then
echo "Vui long nhap ten mien."
sleep 5
/usr/local/mbmenu/action/domain/add_ftp_user
fi

if [ "$domain" = '${domain/.}' ];
then
echo "Ten mien da nhap chua dung, vui long nhap lai!!!"
sleep 6
/usr/local/mbmenu/action/domain/add_ftp_user
fi

if ! grep -R "$domain" $listdomain > /dev/null 2>&1
then
echo "Ten mien chua ton tai tren he thong nen khong the khoi tao FTP Account!!"
sleep 10
fi
. /usr/local/mbmenu/action/ftp/creat_ftp_user $domain
