#!/bin/bash
domain=$1
docroot="/home/admin/domains/$domain"
listdomain="/usr/local/mbmenu/action/domain/listdomain"
listftp="/usr/local/mbmenu/action/ftp/listftp"

gen_user() {
    head /dev/urandom | tr -dc 0-9 | head -c 5
}
usergen=$(gen_user)
user=$(echo "$domain" | cut -f1 -d".")
userftp=$(echo "$user"_"$usergen")
gen_pass() {
    head /dev/urandom | tr -dc a-z0-9 | head -c 14
}
passwd=$(gen_pass)
cd /etc/proftpd
echo $passwd | ftpasswd --stdin --passwd --name=$userftp --gid=33 --uid=33 --home=/home/admin/domains/$domain/ --shell=/bin/false

echo "Them FTP account cho ten mien $domain thanh cong!!!"
echo 
echo "Quay ve menu chinh..."

sleep 10
clear
echo $userftp 
echo $ftppasswd
/usr/local/mbmenu/mbftp
