#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "21. Thiep lap SSL Paid > Xoa cau hinh SSL"
echo "/-----------------------------------------------------------------------/"
echo
selects=()
for entry in `ls -A /etc/nginx/conf.d | grep "_bk"`; do
    domain=$( echo $entry | sed 's/_bk//')
    if [ "$domain" != "${domain/.}" ]; then
        selects+=("$domain")
    fi
done

PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}
do
    domain=$select
    break;
done

if [[ -z "$selects" ]]; then
    echo "Khong co Domain nao ton tai."
    action_ssl_manager
fi

if [[ "$domain" = "" || "$domain" = "0" ]]; then
    action_ssl_manager
fi

username=${domain//[-._]/}

read -p "Ban co muon xoa cau hinh SSL $domain (y/N): " confirm_remove


if [[ "$confirm_remove" = "y" ]]; then
    rm -f /home/$username/$domain/ssl/$domain.conf
    rm -f /etc/nginx/conf.d/$domain.conf
    mv /etc/nginx/conf.d/${domain}_bk /etc/nginx/conf.d/${domain}.conf
    clear
    nginx -t && service nginx reload
    echo "Da xoa cau hinh SSL $domain"
fi
action_ssl_manager