#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
. /etc/larvps/menu/active_check

clear
echo "--//---------------------------------------------------------------------"
echo "1. Quan ly Domain > Them domain"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-5-3"
echo "/-----------------------------------------------------------------------/"
echo

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
phpfpm="$(systemctl status php-fpm.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
mariadb="$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
if [[ "$nginx" != 'active' ]] || [[ "$phpfpm" != 'active' ]] || [[ "$mariadb" != 'active' ]]; then
clear
echo "-------------------------------------------------------------------------"
echo "Co loi xay ra:"
echo "-------------------------------------------------------------------------"
echo "Vui long kiem tra các service truoc khi them ten mien:"
echo "/------------------------------------------------------------------------/"
echo "Nginx: $nginx"
echo "PHP-FPM: $phpfpm"
echo "MariaDB: $mariadb"
echo "/------------------------------------------------------------------------/"
sleep 3
action_domain 
fi
    
domain=$1
if [ -z "$domain" ]; then
read -p "Nhap domain hoac subdomain ban muon them 
    (vidu: larvps.com, abc.larvps.com) [0=Thoat]: " domain
fi


if [[ "$domain" = "0" ]]; then
    clear
    action_domain
fi

if [ "$domain" = '' ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_domain
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_domain
fi

# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ -f "$path" ]]; then
    clear
    echo "Domain da ton tai tren VPS."
    echo
    action_domain
fi

. /etc/larvps/menu/action/domain/create_template $domain