#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
domain=$1
username=${domain//[-._]/}
password=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
sleep 1
password_auth=$(date +%s | sha256sum | base64 | head -c 24 ; echo)
echo
read -p "Ban co muon cai dat SSL (Let's Encrypt) ?  
Yeu cau: Domain da tro IP ve VPS. (y/n): " confirm_ssl
echo
read -p "Ban co muon cai dat Wordpress cho $domain? (y/n): " confirm_wp
echo
if [[ "$confirm_wp" = "y" ]]; then
read -p "Mac dinh se thay prefix wp_ de bao mat (y/n): " has_prefix   
fi
echo
if [[ "$confirm_wp" = "n" ]]; then
read -p "Ban co muon cai Laravel phien ban moi nhat cho $domain? (y/n): " confirm_laravel 
fi


c_db_name=$(date +%s | sha256sum | base64 | head -c 8 ; echo)

if [[ "$confirm_wp" = "y" ]] || [[ "$confirm_laravel" = "y" ]]; then
    db_name=${username}_db
    db_user=${username}_user
    db_password=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
else
    read -p "Bạn có muốn tạo sẵn Database cho $domain? (y/n): " confirm_cb
    if [[ "$confirm_cb" = 'y' ]]; then
        db_name=${username}_db
        db_user=${username}_user
        db_password=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
    fi
fi


# Tạo user và đổi pass
useradd $username

# pass ftp
change_pass=$(expect -c "
spawn passwd $username
expect \"New password\"
send \"$password\r\"
expect \"Retype new password\"
send \"$password\r\"
expect eof
")
echo $change_pass

## pass http auth
ass_secure=$(expect -c "
spawn htpasswd /usr/share/nginx/larvps/passwd/.htpasswd $username
expect \"New password\"
send \"$password_auth\r\"
expect \"Retype new password\"
send \"$password_auth\r\"
expect eof
")
echo $pass_secure


#Tạo thư mục quản lý web
mkdir -p /home/$username/$domain/public_html
mkdir -p /home/$username/$domain/logs
mkdir -p /home/$username/$domain/tmp
mkdir -p /home/$username/$domain/ssl
mkdir -p /home/$username/$domain/session
mkdir -p /home/$username/$domain/restore


chmod 755 /home/$username
chmod 755 /home/$username/$domain/public_html
chmod 700 /home/$username/$domain/logs
chmod 700 /home/$username/$domain/tmp
chmod 700 /home/$username/$domain/ssl
chmod 700 /home/$username/$domain/session
chmod 700 /home/$username/$domain/restore

# chown
chown root:root /home/$username
chown -hR $username:$username /home/$username/$domain/
chmod g+s /home/$username/$domain/public_html

# add group
usermod -G sftp_users $username

cat > "/home/$username/$domain/public_html/index.html" <<END
<h1>Ban da cai dat LarVPS thanh cong.</h1>
END

chcon -R -t httpd_sys_content_t /home/$username/$domain/public_html
chcon -R -t httpd_sys_rw_content_t /home/$username/$domain/public_html

for (( n = 9001; n <= 9500; n++ )); do
    x=$(grep -rnw '/etc/php-fpm.d/' -e $n >> /dev/null 2>&1 && echo 1)
    if [[ ! $x ]]; then
       port_listen=$n
       break
    fi
done

if [[ "$has_prefix" = "y" ]]; then
prefix=$(date +%s | sha256sum | base64 | head -c 6 | sed -e 's/\(.*\)/\L\1/' ; echo)
else
prefix="wp"
fi


#phpfpm
. /etc/larvps/menu/action/domain/template/phpfpm $domain $username $port_listen

#nginx
. /etc/larvps/menu/action/domain/template/nginx $domain $username $port_listen


#mariadb
if [ "$confirm_cb" = "y" ] || [ "$confirm_wp" = "y" ] || [ "$confirm_laravel" = "y" ]; then
. /etc/larvps/menu/action/domain/template/mariadb $db_name $db_user $db_password
fi


#Cài đặt Laravel
if [ "$confirm_laravel" = "y" ]; then
. /etc/larvps/menu/action/domain/template/laravel $domain $username $db_name $db_user $db_password
fi

#Cài đặt wordpess
if [ "$confirm_wp" = "y" ]; then
. /etc/larvps/menu/action/domain/template/wordpress $domain $username $db_name $db_user $db_password $prefix
fi


# lưu config user
cat > "/etc/larvps/user/.$domain.conf" <<END
[$domain]
username=$username
password=$password_auth
password_sftp=$password
domain=$domain
db_name=$db_name
db_user=$db_user
db_password=$db_password
phpMyAdmin=http://$ip:$port_admin/phpmyadmin
public_html=/home/$username/$domain/public_html
END

restart_nginx
restart_php

#cai dat ssl
if [ "$confirm_ssl" = "y" ]; then
. /etc/larvps/menu/action/lets_encrypt/create $domain
fi

clear
echo
echo "Cam on ban da su dung LarVPS"
echo "Ban da them domain thanh cong. Hay luu lai thong tin de su dung ve sau"
echo "-------------------------------------------------------------------------"
echo "1.  Domain                : $domain"
echo "2.  DB_Name               : $db_name"
echo "3.  DB_User               : $db_user"
echo "4.  DB_Password           : $db_password"
echo "6.  PhpMyAdmin            : http://$ip:$port_admin/phpmyadmin"
echo "7.  Username              : $username"
echo "8.  Password_Auth         : $password_auth"
echo "9.  Password_SFTP         : $password"
echo "10. SFTP Host             : $ip"
echo "11. SFTP Port             : $port_ssh"
echo "12. Upload source         : /home/$username/$domain/public_html"
echo "-------------------------------------------------------------------------"
echo
action_domain
