#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//-------------------------------------------------------------------//"
echo "1. Quan ly Domain > Danh sach domain"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-5"
echo "/-----------------------------------------------------------------------/"
echo
list_domain
sleep 3
action_domain


