#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "1. Quan ly Domain > Redirect"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-5-3"
echo "/-----------------------------------------------------------------------/"
echo

count=$(ls -A /etc/larvps/user/ | wc -l)
if [[ "$count" -gt "0" ]]; then
clear
echo "/------------------------------------------------------------------------/"
echo "Ban dang dung phien ban Free, chi ho tro 1 ten mien."
echo "Nang cap: https://larvps.com/pages/pricing"
echo "/------------------------------------------------------------------------/"
sleep 3 
action_domain
fi

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
if [[ "$nginx" != 'active' ]]; then
clear
echo "-------------------------------------------------------------------------"
echo "Co loi xay ra:"
echo "-------------------------------------------------------------------------"
echo "Vui long kiem tra các service truoc khi them ten mien:"
echo "/------------------------------------------------------------------------/"
echo "Nginx: $nginx"
echo "/------------------------------------------------------------------------/"
sleep 3
action_domain 
fi
    
read -p "Nhap domain cua ban [0=Thoat]: " domain

if [[ "$domain" = "0" ]]; then
    clear
    action_domain
fi

if [ "$domain" = '' ]; then
    clear
    echo "Ban chua nhap Domain."
    echo
    action_domain
fi

if [ "$domain" = "${domain/.}" ]; then
    clear
    echo "Domain ban nhap khong dung dinh dang."
    echo
    action_domain
fi


# kiem tra ton tai
mkdir -p /etc/larvps/redirect
path_redirect="/etc/nginx/conf.d/${domain}_redirect.conf"
if [[ -f "$path_redirect" ]]; then
    clear
    read -p "Domain da ton tai cau hinh Redirect tren VPS. Ban co muon xoa (y/n): " confirm
    if [[ "$confirm" = "y" ]]; then
        rm -f $path_redirect
        nginx -t && service nginx restart
        clear
        echo "Da xoa redirect $domain"
    fi
    action_domain
fi


# kiem tra ton tai
path="/etc/larvps/user/.$domain.conf"
if [[ -f "$path" ]]; then
    clear
    echo "Domain da them tren VPS. Vui long xoa neu muon su dung Redirect"
    echo
    action_domain
fi


read -p "Nhap domain ban muon Redirect: " des_domain




cat > "/etc/nginx/conf.d/${domain}_redirect.conf" <<END
server {
    listen 80;
    server_name www.$domain $domain;
    return 301 \$scheme://$des_domain\$request_uri;
}
END

nginx -t && service nginx restart
clear
echo "Da them Redirect $domain sang $des_domain"
action_domain