#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//-------------------------------------------------------------------//"
echo "1. Quan ly Domain > Restore Nginx"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-5"
echo "/-----------------------------------------------------------------------/"
echo

domain=$1
if [ -z "$domain" ] ; then
get_choose_domain
fi

find /etc/nginx/conf.d | grep ${domain} | xargs rm -f

username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
. /etc/larvps/menu/action/domain/template/nginx $domain $username $port_listen
clear

nginx -t && service nginx restart
action_domain


