#!/bin/bash
chon_php () {
echo "Vui long lua chon phien ban PHP-FPM (5.6 -> 7.4)"
echo "1. PHP-FPM 5.6"
echo "2. PHP-FPM 7.0"
echo "3. PHP-FPM 7.1"
echo "4. PHP-FPM 7.2"
echo "5. PHP-FPM 7.3"
echo "6. PHP-FPM 7.4"
echo "Vui long chon (1-6):"
read chonphp

if [ $chonphp -eq 1 ]
then
     php_version=php5.6-fpm
elif [ $chonphp -eq 2 ]
then
     php_version=php7.0-fpm
elif [ $chonphp -eq 3 ]
then
     php_version=php7.1-fpm
elif [ $chonphp -eq 4 ]
then
     php_version=php7.2-fpm
elif [ $chonphp -eq 5 ]
then
        php_version=php7.3-fpm
elif [ $chonphp -eq 6 ]
then
     php_version=php7.4-fpm
else
        clear
     echo "Ban da chon so khong co trong Menu"
     echo "Vui long thu lai"
chon_php
fi
     }
clear
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "- 1. Quan ly Domain : $(apache2 -v | cut -f3 -d' ' | head -1) - $(systemctl status apache2.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo
echo "--//---------------------------------------------------------------------"
echo "- 1. Quan ly Domain > Them ten mien moi"
echo "/-----------------------------------------------------------------------/"
echo ""

domain=$1
php_version=$2
if [ -z "$domain" ]; then
read -p "Nhap domain hoac subdomain moi (vi du: matbao.net, wiki.matbao.net) [5=Quay lai]: " domain
fi

if [ "$domain" = "5" ];
then
echo "Quay lai menu chinh..."
sleep 5
/usr/local/mbmenu/mbdomain
fi

if [ "$domain" = '' ];
then
echo "Vui long nhap ten mien."
sleep 5
/usr/local/mbmenu/action/domain/create_vhost
fi

if [ "$domain" = '${domain/.}' ];
then
echo "Ten mien da nhap chua dung, vui long nhap lai!!!"
sleep 8
/usr/local/mbmenu/action/domain/create_vhost
fi


dir="/home/admin/conf/$domain.conf"
if [[ -f "$dir" ]];
then
echo "Ten mien da ton tai tren may chu, vui long nhap lai!!"
sleep 10
/usr/local/mbmenu/action/domain/create_vhost
fi

chon_php

. /usr/local/mbmenu/action/domain/add_vhost $domain $php_version

