#!/bin/bash
clear
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "- 1. Quan ly Domain : $(apache2 -v | cut -f3 -d' ' | head -1) - $(systemctl status apache2.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo "//---------------------------------------------------------------------//"
echo
echo "--//---------------------------------------------------------------------"
echo "1. Quan ly Domain > Xoa domain"
echo "-------------------------------------------------------------------------"
echo "/-----------------------------------------------------------------------/"
echo

domain=$1
if [ -z "$domain" ]; then
read -p "Nhap domain can xoa [5=Quay lai]: " domain
fi

dir="/home/admin/conf/$domain.conf"
if [[ ! -f "$dir" ]]; then
    echo "Domain khong ton tai tren may chu."
fi

echo -n "Ban chac chan muon xoa ten mien $domain? (Y/n): "
read ok

if [ $ok = "Y" -o $ok = "y" ];
then
echo "Thuc hien xoa ten mien $domain khoi may chu..."
sleep 5

rm -rf /home/admin/conf/$domain.conf
rm -rf /home/admin/domains/$domain
sed -i '/'$domain'/d' /usr/local/mbmenu/action/domain/listdomain

/etc/init.d/apache2 restart >/dev/null 2>&1

echo "Da xoa xong ten mien $domain"
sleep 4
/usr/local/mbmenu/mbdomain
else [ $ok = "n" -o $ok = "N" ];
echo "Quay tro lai menu"
sleep 4
/usr/local/mbmenu/mbdomain
fi
