#!/bin/bash
domain=$1
php_version=$2
cat > "/home/admin/conf/$domain.conf" <<END
<VirtualHost *:80>
    ServerAdmin webmaster@example.com
    DocumentRoot "/home/admin/domains/$domain/public_html"
    ServerName $domain
    ServerAlias www.$domain
    #errorDocument 404 /404.html
    ErrorLog "/home/admin/domains/$domain/logs/$domain-error_log"
    CustomLog "/home/admin/domains/$domain/logs/$domain-access_log" combined
    
    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>
    
    #PHP
    <FilesMatch \.php$>
            SetHandler "proxy:unix:/run/php/$PHP-fpm.sock|fcgi://localhost"
    </FilesMatch>
    
    #PATH
    <Directory "/home/admin/domains/$domain/public_html">
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>
</VirtualHost>
<VirtualHost *:443>
        DocumentRoot "/home/admin/domains/$domain/public_html"
        SSLEngine on
        SSLCertificateFile /home/admin/domains/$domain/ssl/$domain.crt
        SSLCertificateKeyFile /home/admin/domains/$domain/ssl/$domain.key
        SSLCertificateChainFile /home/admin/domains/$domain/ssl/CA.crt
            ServerName $domain
    ServerAlias www.$domain
    #errorDocument 404 /404.html
    ErrorLog "/home/admin/domains/$domain/logs/$domain-error_log"
    CustomLog "/home/admin/domains/$domain/logs/$domain-access_log" combined
    
    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>
    
    #PHP
    <FilesMatch \.php$>
            SetHandler "proxy:unix:/run/php/$php_version.sock|fcgi://localhost"
    </FilesMatch>
    
    #PATH
    <Directory "/home/admin/domains/$domain/public_html">
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>
</VirtualHost>
END
