#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Them SSL - Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-6-10"
echo "/-----------------------------------------------------------------------/"
echo

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"

if [[ "$nginx" != "active" ]]; then
    clear
    echo "Nginx hien tai khong hoat dong. Vui long kiem tra lai."
    echo
    action_lets_encrypt
fi

if [[ ! -f ~/.acme.sh/acme.sh ]]; then
wget -O -  https://get.acme.sh | sh
source  ~/.bashrc
clear
fi
domain=$1
if [ -z "$domain" ] ; then
get_choose_domain
fi
username=${domain//[-._]/}
sub=0
check_sub=($(echo $domain | tr '.' "\n"))

if [[ -f /root/.acme.sh/$domain/fullchain.cer ]]; then
clear
echo "Domain da duoc cau hinh SSL Let's Encrypt"
sleep 2
action_lets_encrypt
fi

# kiem tra paid ssl
if [[ -f /home/$username/$domain/ssl/$domain.conf ]]; then
    clear
    echo "Domain da duoc cau hinh SSL Paid truoc do. Vui long xoa o module 21"
    action_ssl_manager
fi

#cerbot cu
if [[ -f /etc/larvps/lets_encrypt/${domain}.conf ]]; then
mv /etc/larvps/lets_encrypt/${domain}.conf /etc/nginx/conf.d/${domain}.conf
rm -rf /etc/larvps/lets_encrypt/${domain}.conf
fi

#tao ssl
if [[ "${#check_sub[@]}" < "3" ]]; then
~/.acme.sh/acme.sh --issue --nginx -d $domain -d www.$domain --debug
else
~/.acme.sh/acme.sh --issue --nginx -d $domain --debug
fi

if [[ ! -f /root/.acme.sh/$domain/fullchain.cer ]]; then
clear
echo "Cai dat Let's Encrypt that bai"
sleep 2
action_lets_encrypt
fi


#tat nginx
path_nginx_ssl=/etc/nginx/conf.d/${domain}_ssl.bk
if [[ ! -f $path_nginx_ssl ]]; then
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
. /etc/larvps/menu/action/domain/template/nginx_ssl $domain $username $port_listen
fi

mv /etc/nginx/conf.d/${domain}_ssl.bk /etc/nginx/conf.d/${domain}_ssl.conf
mv /etc/nginx/conf.d/${domain}.conf /etc/nginx/conf.d/${domain}_non_ssl.bk

service nginx restart

if [ -z "$1" ]; then
action_lets_encrypt
fi