#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Them SSL - Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-6-10"
echo "/-----------------------------------------------------------------------/"
echo

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"

if [[ "$nginx" != "active" ]]; then
    clear
    echo "Nginx hien tai khong hoat dong. Vui long kiem tra lai."
    echo
    action_lets_encrypt
fi


if [[ ! -f "/usr/bin/certbot" ]]; then
clear
echo "Khong tim thay file du lieu. Vui long cap nhat."
action_lets_encrypt
fi

domain=$1
if [ -z "$domain" ] ; then
get_choose_domain
fi

# echo $domain
# echo $username
# echo $index
# echo $path

sub=0
check_sub=($(echo $domain | tr '.' "\n"))



if [[ -f /etc/larvps/lets_encrypt/${domain}.conf ]]; then
read -p "Domain da cai dat SSL. Ban co muon Renew (y/n)?" confirm
if [[ "$confirm" != "y" ]]; then
clear
action_lets_encrypt
fi
fi

mkdir -p /etc/larvps/lets_encrypt_backup

#
if [[ ! -f /etc/nginx/conf.d/${domain}.conf ]]; then
mv /etc/nginx/conf.d/${domain}.bk /etc/nginx/conf.d/${domain}.conf
mv /etc/nginx/conf.d/${domain}_non_ssl.bk /etc/nginx/conf.d/${domain}.conf
mv /etc/nginx/conf.d/${domain}_ssl.conf /etc/nginx/conf.d/${domain}_ssl.bk
fi


if [[ ! -f /etc/nginx/conf.d/${domain}.conf ]]; then
clear
echo "Khong tim thay file config /etc/nginx/conf.d/${domain}.conf"
sleep 2
action_lets_encrypt
fi

# lưu config nginx
yes | cp -rf "/etc/nginx/conf.d/${domain}.conf" "/etc/larvps/lets_encrypt/${domain}.conf"
yes | cp -rf "/etc/nginx/conf.d/${domain}.conf" "/etc/larvps/lets_encrypt_backup/${domain}_http.conf"

if [[ "${#check_sub[@]}" < "3" ]]; then
certbot --nginx --expand -d $domain -d 'www.'$domain
else
certbot --nginx --expand -d $domain
fi
	
if [[ ! -d /etc/letsencrypt/archive/${domain} ]]; then
echo "Cai dat Let's that bai"
sleep 2
action_lets_encrypt
fi

# certbot --nginx --no-bootstrap

# set http2
sed -i "s/443 ssl; #/443 ssl http2; #/g" /etc/nginx/conf.d/$domain.conf

# restart
restart_nginx

yes | cp -rf "/etc/nginx/conf.d/${domain}.conf" "/etc/larvps/lets_encrypt_backup/${domain}_https.conf"

if [ -z "$1" ]; then
action_lets_encrypt
fi