#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Gia han thu cong - Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-6-11"
echo "/-----------------------------------------------------------------------/"
echo

if [[ "$nginx" != "active" ]]; then
    clear
    echo "Nginx hien tai khong hoat dong. Vui long kiem tra lai."
    echo
    action_lets_encrypt
fi

domain=$1
if [ -z "$domain" ] ; then
get_choose_domain
fi
username=${domain//[-._]/}
sub=0
check_sub=($(echo $domain | tr '.' "\n"))

if [[ ! -f /root/.acme.sh/$domain/${domain}.key ]]; then
clear
echo "Domain chua cau hinh SSL Let's Encrypt"
sleep 2
get_choose_domain
fi

#cerbot cu
if [[ -f /etc/larvps/lets_encrypt/${domain}.conf ]]; then
mv /etc/larvps/lets_encrypt/${domain}.conf /etc/nginx/conf.d/${domain}.conf
rm -rf /etc/larvps/lets_encrypt/${domain}.conf
fi

#tao ssl
if [[ "${#check_sub[@]}" < "3" ]]; then
~/.acme.sh/acme.sh --issue --nginx -d $domain -d www.$domain
else
~/.acme.sh/acme.sh --issue --nginx -d $domain
fi

#tat nginx
path_nginx_ssl=/etc/nginx/conf.d/${domain}_ssl.bk
if [[ ! -f $path_nginx_ssl ]]; then
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
. /etc/larvps/menu/action/domain/template/nginx_ssl $domain $username $port_listen
fi

mv /etc/nginx/conf.d/${domain}_ssl.bk /etc/nginx/conf.d/${domain}_ssl.conf
mv /etc/nginx/conf.d/${domain}.conf /etc/nginx/conf.d/${domain}_non_ssl.bk

service nginx restart

if [ -z "$1" ]; then
action_lets_encrypt
fi


action_lets_encrypt
