#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "2. Quan ly Let's Encrypt > Them Wildcard SSL"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-6-10"
echo "/-----------------------------------------------------------------------/"
echo

nginx="$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"

if [[ "$nginx" != "active" ]]; then
    clear
    echo "Nginx hien tai khong hoat dong. Vui long kiem tra lai."
    echo
    action_lets_encrypt
fi

# domain=$1
# if [ -z "$domain" ] ; then
# get_choose_domain
# fi

# if [[ ! -f /etc/larvps/lets_encrypt/${domain}.conf ]]; then
# clear
# echo "Vui long cai SSL Let's cho Domain truoc khi su dung Wildcard SSL"
# sleep 3
# action_lets_encrypt
# fi

if [[ ! -f "/usr/bin/certbot" ]]; then
echo "Khong tim thay file du lieu. Vui long cap nhat."
action_lets_encrypt
fi

echo "Huong dan:"
echo "Phuc vu: WP Multi Domains, Muli Subdomain"
echo "Cau truc: domain.com *.domain.com"
echo "Vi du: larvps.com *.larvps.com (* ở đây là cho N subdomain)"
echo "Tren DNS của Domain ban tao Record: Type: text, Name: _acme-challenge, Value: Nhap ma do Lets cap"
echo
echo


if [[ -f "/etc/letsencrypt/live/${domain}/fullchain.pem" ]]; then
read -p "Domain da cai dat SSL. Ban co muon Renew (y/n)?" confirm
if [[ "$confirm" != "y" ]]; then
clear
action_lets_encrypt
fi
fi

rm -rf /etc/letsencrypt/live/${domain}-0001
rm -rf /etc/letsencrypt/archive/${domain}-0001
rm -rf /etc/letsencrypt/renewal/${domain}-0001.conf

rm -rf /etc/letsencrypt/live/${domain}
rm -rf /etc/letsencrypt/archive/${domain}
rm -rf /etc/letsencrypt/renewal/${domain}.conf

certbot certonly --manual --server https://acme-v02.api.letsencrypt.org/directory

if [[ ! -f "/etc/letsencrypt/live/${domain}/fullchain.pem" ]]; then
echo "Cai dat that bai"
action_lets_encrypt
fi

username=${domain//[-._]/}
port_listen=$(cat /etc/php-fpm.d/$domain.conf | grep "127.0.0.1:" | cut -f2 -d":")
. /etc/larvps/menu/action/domain/template/nginx_wildcard $domain $username $port_listen

restart_nginx

action_lets_encrypt