#!/bin/bash
echo "-------------------------------------------------------------------------"
echo "5. Quan ly Database > Thay doi Password User"
echo "-------------------------------------------------------------------------"
echo ""
read -p "Nhap User: " user


if [[ "$user" = "" ]]; then
  echo "Ban chua nhap user"
  exit 0
fi

read -p "Nhap_Password: " password
read -p "Xac nhan thay doi password cho user $user? (y/n): " confirm

if [[ "$password" = "" ]]; then
  echo "Mat khau khong de trong"
  exit 0
fi


if [[ "$confirm" = 'y' ]]; then
        echo "Dang tien hanh thay doi password..."
        sleep 1
    db_admin_password=$(cat /usr/local/mbmenu/data/.my.cnf)
    mysql -u root -p"$db_admin_password" -e "SET PASSWORD FOR '$user'@'localhost' = PASSWORD('$password')"
    echo "Da thay doi password thanh cong"
fi
