#!/bin/bash
echo "--//---------------------------------------------------------------------"
echo "- 5. Quan ly database > Them database va User"
echo "/-----------------------------------------------------------------------/"
echo ""

read -p "1. Nhap DB_Name: " database
read -p "2. Nhap DB_User: " username
read -p "3. Nhap DB_Password: " password
read -p "Xac nhan them database? (y/n): " confirm

if [ "$database" = "" ] || [ "$username" = "" ] || [ "$password" = "" ]; then
    clear
fi

if [[ "$confirm" = "y" ]]; then
        echo "Dang tien hanh them database moi..."
    # mysql -u admin -p"$db_admin_password" -e "show DATABASEs"
    db_admin_password=$(cat /usr/local/mbmenu/data/.my.cnf)
    mysql -u root -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $database"
    mysql -u root -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$username'@'localhost' IDENTIFIED BY '$password'"
    mysql -u root -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $database.* TO '$username'@'localhost'"
    mysql -u root -p"$db_admin_password" -e "FLUSH PRIVILEGES"
    echo "Da Them Thanh Cong"
    echo
    echo "DB_Name: " $database
    echo "DB_User: " $username
    echo "DB_Password: " $password
    echo
fi
