#!/bin/bash
echo "-------------------------------------------------------------------------"
echo "5.Quan ly Database > Xóa database"
echo "-------------------------------------------------------------------------"
echo ""

echo "Danh sách Database"
db_admin_password=$(cat /usr/local/mbmenu/data/.my.cnf)
mysql -u root -p"$db_admin_password" -e "show databases where \`database\` not in('information_schema', 'test', 'sys', 'phpmyadmin', 'mysql', 'performance_schema')"
echo

read -p "Nhap ten database can xóa: " database
read -p "Xac nhan xoa dabase? (y/n): " confirm

if [ "$database" = "" ]; then
 echo "Ban can nhap database can xoa"
 exit 0
fi

if [[ "$confirm" = "y" ]]; then
        echo "Dang tien hanh xoa database..."
        sleep 1
    mysql -u root -p"$db_admin_password" -e "DROP DATABASE $database"
    echo "Da xoa database thanh cong"
fi
