#!/bin/bash
domain=$1
username=$2

if [[ ! -f /usr/local/bin/composer ]]; then
    echo "Đang cài đặt Composer..."
    sleep 1
    cd
	if [[ ! -f /var/swap.1 ]]; then
	/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=2048
	/sbin/mkswap /var/swap.1
	/sbin/swapon /var/swap.1
	fi
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -d memory_limit=-1 composer-setup.php
    php -r "unlink('composer-setup.php');"
    mv composer.phar /usr/local/bin/composer
    clear
fi

echo "Đang tiến hành cài đặt Laravel phiên bản mới nhất ...."
sleep 1
rm -rf /home/$username/$domain/public_html/*
cd /home/$username/$domain/public_html/
composer create-project --prefer-dist laravel/laravel ./

# set db
sed -i "s/APP_ENV=local/APP_ENV=production/g" /home/$username/$domain/public_html/.env
sed -i "s/DB_DATABASE=laravel/DB_DATABASE=$db_name/g" /home/$username/$domain/public_html/.env
sed -i "s/DB_USERNAME=root/DB_USERNAME=$db_user/g" /home/$username/$domain/public_html/.env
sed -i "s/DB_PASSWORD=/DB_PASSWORD=$db_password/g" /home/$username/$domain/public_html/.env

# set chown
chown -R $username:$username /home/$username/$domain/public_html
chmod -R a=r,u+w,a+X /home/$username/$domain/public_html

# tro public
sed -i "s/$domain\/public_html;/$domain\/public_html\/public;/g" /etc/nginx/conf.d/$domain.conf
