#!/bin/bash
. /etc/larvps/.larvps.conf
db_name=$1
db_user=$2
db_password=$3

mysql -u admin -p"$db_admin_password" -e "DROP DATABASE IF EXISTS $db_name"
mysql -u admin -p"$db_admin_password" -e "CREATE DATABASE IF NOT EXISTS $db_name"
mysql -u admin -p"$db_admin_password" -e "DROP USER IF EXISTS '$db_user'@'localhost'"
mysql -u admin -p"$db_admin_password" -e "CREATE USER IF NOT EXISTS '$db_user'@'localhost' IDENTIFIED BY '$db_password'"
mysql -u admin -p"$db_admin_password" -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_user'@'localhost'"
mysql -u admin -p"$db_admin_password" -e "FLUSH PRIVILEGES"
