#!/bin/bash
domain=$1
username=$2
port_listen=$3

cat > "/etc/php-fpm.d/$domain.conf" <<END
[$domain]
listen = 127.0.0.1:$port_listen
user = $username
group = $username
listen.mode = 644
listen.allowed_clients = 127.0.0.1
pm = ondemand
pm.max_children = 5
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 4
pm.max_requests = 500
request_terminate_timeout = 300
php_admin_value[open_basedir] = /home/$username/$domain:/tmp
php_admin_value[upload_tmp_dir] = /home/$username/$domain/tmp:/tmp
php_admin_value[session.safe_path] = /home/$username/$domain/session
php_admin_value[error_log] = /home/$username/$domain/logs/php_error_log
php_admin_value[session.save_path] = /home/$username/$domain/session
END
