#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
clear
echo "--//---------------------------------------------------------------------"
echo "17. Quan ly Log > Mariadb"
echo "/-----------------------------------------------------------------------/"

cat /var/log/mysql/mysql.log | sort -r | head -15
sleep 3
action_log_manager