#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

count=$(ls -A /etc/larvps/user/ | wc -l)
if [[ ! -f "/etc/larvps/menu/mod_security" ]]; then
	if [[ "$count" -gt "0" ]]; then
		clear
		echo "/------------------------------------------------------------------------/"
		echo "Ban dang dung phien ban Free, chi ho tro 1 ten mien."
		echo "Nang cap: https://larvps.com/pages/pricing"
		echo "/------------------------------------------------------------------------/"
		sleep 3
		action_domain
	fi
fi

if [[ "$count" -ge "1" ]]; then
	clear
	echo "/------------------------------------------------------------------------/"
	echo "Ban dang dung phien ban, chi ho tro cho 1 ten mien."
	echo "Nang cap: https://larvps.com/pages/pricing"
	echo "/------------------------------------------------------------------------/"
	sleep 3
	action_domain	
fi