#!/bin/bash
echo "==//====================================================================="
echo "9. Quan ly Application"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-13"
echo "/-----------------------------------------------------------------------/"
echo
options=(
	"Cai dat Wordpress" 
	"Cai dat Laravel"
	)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/application/wordpress'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/application/laravel'
            ;;
        *) larvps;;
    esac
done