#!/bin/bash
. /etc/larvps/.larvps.conf
latest_version=$(curl -s https://larvps.com/scripts/info | grep "latest_version=" | cut -f2 -d'=')
if [[ "$latest_version" != "$version" ]]; then
   clear
   echo "==//===================================================================="
   echo "Thong bao cap nhat - Ban dang su dung: v$version"
   echo "-------------------------------------------------------------------------" 
   echo "Da co ban cap nhat v$latest_version."
   echo "Go lenh: larvps update hoac 01 de cap nhat."
   echo "/-----------------------------------------------------------------------/"
fi