#!/bin/bash
. /etc/larvps/menu/functions
echo
echo "==//====================================================================="
echo "- 5. Quan ly Database - MariaDB: $(mysql --version | cut -f6 -d' ' | cut -f1 -d'-') - $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-------------------------------------------------------------------------"
echo "- Huong dan: https://larvps.com/pages/documentation/all#section-10"
echo "/-----------------------------------------------------------------------/"
echo
echo "/-----------------------------------------------------------------------/"
echo "phpMyAdmin: http://$ip:$port_admin/phpmyadmin"
echo "-------------------------------------------------------------------------"
echo "PortAdmin: $port_admin"
echo "Username: admin"
echo "Password auth: $ad_password"
echo "Password admin mysql: $db_admin_password"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Danh sach Database"
    "Thong tin Database"
    "Them Database"
    "Thay doi password DB_User"
    "Xoa Database"
    "Import Database"
    "Export Database"
    )
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/database/list'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/database/info'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/database/create'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/database/change_password'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/action/database/delete'
            ;;
        "${options[5]}")
            '/etc/larvps/menu/action/database/import'
            ;;
        "${options[6]}")
            '/etc/larvps/menu/action/database/export'
            ;;
        *) larvps;;
    esac
done

