#!/bin/bash
. /etc/larvps/menu/functions
disk=$(mount|grep ' / '|cut -d' ' -f 1)
total_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $3}' | tr -d 'a-zA-G')
use_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $4}' | tr -d 'a-zA-G')

echo
echo "==//====================================================================="
echo "16. Quan ly Disk - ${total_disk}GB (used: ${use_disk}GB)"
echo "-------------------------------------------------------------------------"
disk=$(mount|grep ' / '|cut -d' ' -f 1)
echo "Filesystem     Type       Size Used  Avail Use% Mounted on"
echo "$(df -T -h | grep $disk)"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Canh bao FullDisk"
    "Check Root"
    "Check Home"
    "Check Var"
    "Check Tmp"
    "Check Usr"
    "Large files"
    "Large file domain"
    # "Gioi han Disk Domain"
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            "/etc/larvps/menu/action/disk_manager/fulldisk"
            ;;
        "${options[1]}")
            "/etc/larvps/menu/action/disk_manager/disk_root"            
            ;;
        "${options[2]}")
            "/etc/larvps/menu/action/disk_manager/disk_home"            
            ;;
        "${options[3]}")
            "/etc/larvps/menu/action/disk_manager/disk_var"            
            ;;
        "${options[4]}")
            "/etc/larvps/menu/action/disk_manager/disk_tmp"            
            ;;
        "${options[5]}")
            "/etc/larvps/menu/action/disk_manager/disk_usr"            
            ;;
        "${options[6]}")
            "/etc/larvps/menu/action/disk_manager/large_files"            
            ;;
        "${options[7]}")
            "/etc/larvps/menu/action/disk_manager/find_large_files"            
            ;;
        *) larvps;;
    esac
done