#!/bin/bash
echo
echo "==//====================================================================="
echo "8. Quan ly Fail2ban"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#item-23"
echo "/-----------------------------------------------------------------------/"
echo
options=("Danh sach IP bi khoa" "Danh sach IP da mo khoa" "Khoa IP" "Mo khoa IP")
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/fail2ban/list'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/fail2ban/unlist'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/fail2ban/block'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/fail2ban/unblock'
            ;;
        *) larvps;;
    esac
done

