#!/bin/bash
echo
echo "==//====================================================================="
echo "19. Quan ly Image"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Optimize Images (JPG+PNG)"
)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in 
        "${options[0]}")
            '/etc/larvps/menu/action/image_manager/list'
            ;;
        *) larvps;;
    esac
done