#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

totalRam=$(cat /proc/meminfo | grep 'MemTotal' |cut -f2 -d':' | xargs | cut -f1 -d' ')
memAvailable=$(cat /proc/meminfo | grep 'MemAvailable' |cut -f2 -d':' | xargs | cut -f1 -d' ')
totalSwap=$(cat /proc/meminfo | grep 'SwapTotal' |cut -f2 -d':' | xargs | cut -f1 -d' ')
freeSwap=$(cat /proc/meminfo | grep 'SwapFree' |cut -f2 -d':' | xargs | cut -f1 -d' ')
disk=$(mount|grep ' / '|cut -d' ' -f 1)
total_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $3}' | tr -d 'a-zA-G')
available_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $5}' | tr -d 'a-zA-G')

clear
printf "=========================================================================\n"
printf "                       Info VPS - IP: $ip\n"
printf "=========================================================================\n"
echo ""
echo ""
echo "Active"
echo "$(uptime | xargs)"
echo ""

echo "CPU loading  : $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')"
echo "Ram          : $(human $totalRam) (available: $(human $memAvailable))"
echo "Swap         : $(human $totalSwap) (available: $(human $freeSwap))"
echo "Disk         : ${total_disk}GB (available: ${available_disk}GB)"
echo
echo "CPU"
echo "-------------------------------------------------------------------------"
echo "Total Core   : $(cat /proc/cpuinfo | grep 'processor' | wc -l)"
echo "CPU Model    : $(cat /proc/cpuinfo  | grep 'name'| uniq | cut -f2 -d':' | xargs)"
echo "CPU MHz      : $(cat /proc/cpuinfo | grep 'cpu MHz' | cut -f2 -d':' | xargs)"
echo "Cache Size   : $(cat /proc/cpuinfo | grep 'cache size' | cut -f2 -d':' | xargs)"
echo ""

echo "Manager Service"
echo "-------------------------------------------------------------------------"
echo "Nginx        : $(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "Php-FPM      : $(systemctl status php-fpm.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "MariaDB      : $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "Fail2Ban     : $(systemctl status fail2ban.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "SSHD         : $(systemctl status sshd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "Crond        : $(systemctl status crond.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "Memcached    : $(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "Redis        : $(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"

echo ""
echo "Firewall"
echo "-------------------------------------------------------------------------"
echo "FW status    : $(firewall-cmd --state)"
echo "Port Open    : $(firewall-cmd --list-ports)"
echo ""

echo "Other"
echo "-------------------------------------------------------------------------"
echo "PHP          : $(rpm -qa php-fpm | cut -f3 -d'-')"
echo "MariaDB      : $(mysql --version | cut -f6 -d' ' | cut -f1 -d'-')"
echo "$(/usr/sbin/nginx -v)"

echo "System"
echo "-------------------------------------------------------------------------"
echo "Virtualization: $(hostnamectl | grep "Virtualization" | cut -f2 -d":" | cut -f2 -d" ")"
echo "System OS     : $(hostnamectl | grep "Operating System" | cut -f2 -d":" | xargs)"
echo "Kernel        : $(hostnamectl | grep "Kernel" | cut -f2 -d":" | xargs)"











