#!/bin/bash

echo "===//===================================================================="
echo "2. Quan ly Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-6"
echo "/-----------------------------------------------------------------------/"
echo
options=(
	"Danh sach da cai SSL"
    "Them + Gia han SSL"
    "Xoa"
    "Them - WildCard SSL"
    "Them - Alias Domain SSL"
    )
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
    	"${options[0]}")
    	    '/etc/larvps/menu/action/lets_encrypt/list'
    	    ;;
        "${options[1]}")
            '/etc/larvps/menu/action/lets_encrypt/create'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/lets_encrypt/delete'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/lets_encrypt/wildcard_ssl'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/action/lets_encrypt/alias_ssl'
            ;;
        *) larvps;;
    esac
done

