#!/bin/bash
clear
if [ "$(ls -A /etc/larvps/user)" ]; then
echo
echo "Danh sách list public_html"
echo '--------------------------------------------------'
  for entry in `ls -A /etc/larvps/user`; do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    username=${domain//[-._]/}
    path="/home/$username/$domain/public_html"
    i=1

    if [[ -d "$path" ]]; then
         echo "cd $path"
    fi
  done
  echo '--------------------------------------------------'
  echo
fi


