#!/bin/bash
echo
echo "==//====================================================================="
echo "17. Quan ly Log"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Nginx"
    "PHP-FPM"
    "MariaDB"
    "Domain"
    "Xoa log (Nginx+PHP-FPM+MariaDB)"
)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            "/etc/larvps/menu/action/log_manager/nginx"
            ;;
        "${options[1]}")
            "/etc/larvps/menu/action/log_manager/php_fpm"            
            ;;
        "${options[2]}")
            "/etc/larvps/menu/action/log_manager/mariadb"            
            ;;
        "${options[3]}")
            "/etc/larvps/menu/action/log_manager/domain"            
            ;;
        "${options[4]}")
            "/etc/larvps/menu/action/log_manager/delete_all"            
            ;;
        *) larvps;;
    esac
done