#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions

if [ "$(ls -At /etc/larvps/user)" ]; then
    clear
    echo "Dang phan quyen cho cac domain:"
    sleep 1
    for entry in `ls -A /etc/larvps/user`; do
        domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
        username=${domain//[-._]/}
        path="/home/$username/$domain"
        chown -hR $username:$username /home/$username/$domain/public_html
        chmod -R a=r,u+w,a+X /home/$username/$domain/public_html

        if [[ -f /home/$username/$domain/public_html/wp-config.php ]]; then
            chmod 400 /home/$username/$domain/public_html/wp-config.php
        fi
        if [[ -f /home/$username/$domain/public_html/index.php ]]; then
            chmod 444 /home/$username/$domain/public_html/index.php
        fi
        if [[ -f /home/$username/$domain/public_html/public/index.php ]]; then
            chmod 444 /home/$username/$domain/public_html/public/index.php
        fi

        chown nginx:nginx /var/lib/php/session
        chmod 755 /var/lib/php/session
    done
    echo "Hoan tat."
else
    clear
    echo "Khong co domain nao ton tai tren he thong."    
fi

