#!/bin/bash
echo
echo "==//====================================================================="
echo "15. Quan ly Port"
echo "/-----------------------------------------------------------------------/"
echo
options=("Danh sach port" "Mo port" "Khoa port" "Mo port can thiet")
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/port/list'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/port/create'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/port/delete'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/port/port_open'
            ;;
        *) larvps;;
    esac
done