#!/bin/bash
echo
echo "==//====================================================================="
echo "3. Quan ly SSH/SFTP"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-7"
echo "/-----------------------------------------------------------------------/"
echo
options=("Doi port SSH/SFTP" "Doi password SSH/SFTP Root" "Doi password SFTP User" "Tang so lan login sai")
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/ssh/change_port'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/ssh/change_password'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/ssh/change_password_user'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/ssh/login_failed'
            ;;
        *) larvps;;
    esac
done

