#!/bin/bash
. /etc/larvps/.larvps.conf
echo
echo "==//====================================================================="
echo "21. Thiet lap SSL Paid"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Them SSL"
    "Xoa SSL"
    "Restart Nginx"
)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/ssl_manager/create'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/ssl_manager/delete'
            ;;
        "${options[2]}")
			clear
			echo "Dang tien hanh khoi dong lai Nginx"
            nginx -t && service nginx restart
            echo "Hoan thanh"
            action_ssl_manager
            ;;
        *) larvps ;;
    esac
done