#!/bin/bash
. /etc/larvps/.larvps.conf
. /etc/larvps/menu/functions
disk=$(mount|grep ' / '|cut -d' ' -f 1)
total_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $3}' | tr -d 'a-zA-G')
available_disk=$(df -T -h | grep $disk | awk -F ' ' '{print $5}' | tr -d 'a-zA-G')
totalRam=$(cat /proc/meminfo | grep 'MemTotal' |cut -f2 -d':' | xargs | cut -f1 -d' ')
memAvailable=$(cat /proc/meminfo | grep 'MemAvailable' |cut -f2 -d':' | xargs | cut -f1 -d' ')
totalSwap=$(cat /proc/meminfo | grep 'SwapTotal' |cut -f2 -d':' | xargs | cut -f1 -d' ')

freeSwap=$(cat /proc/meminfo | grep 'SwapFree' |cut -f2 -d':' | xargs | cut -f1 -d' ')
count_domain=$(ls -At /etc/larvps/user | wc -l)
ip=$(curl -s "https://larvps.com/scripts/ip-address?domain=$count_domain")
# if [[ "$ip" = "update" ]]; then
# sed -i '/version=/d' /etc/larvps/.larvps.conf
# echo "version=5" >>  /etc/larvps/.larvps.conf
# . /etc/larvps/menu/action/larvps_update/update_larvps 1
# clear
# echo "Vui long nang cap Plan de su dung nhieu domain hon"
# echo "Active Key: https://larvps.com/pages/pricing"
# sleep 10
# fi

if [[ "$limit_disk" != "" && "$total_disk" > "0" && "$available_disk" -lt "$limit_disk" ]]; then
clear
echo "-//----------------------------------------------------------------------"
echo "** CANH BAO FULLDISK - DUNG LUONG CON: ${available_disk}GB"
echo "Canh bao khi disk con duoi: ${limit_disk}GB"
echo "/-----------------------------------------------------------------------/"

else
echo
echo "/-----------------------------------------------------------------------/"
echo "Hom nay: $(date +'%d-%m-%Y') - $ip"
echo "/-----------------------------------------------------------------------/"
echo
echo "$(uptime | xargs)"
echo "CPU          : $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')"
echo "Disk         : ${total_disk}GB (available: ${available_disk}GB)"
echo "Ram          : $(human $totalRam) (available: $(human $memAvailable))"
echo "Swap         : $(human $totalSwap) (available: $(human $freeSwap))"
echo "-------------------------------------------------------------------------"
echo "Nginx: $(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs) | PHP-FPM: $(systemctl status php-fpm.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs) | MariaDB: $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-------------------------------------------------------------------------"
echo "Login failed : $(grep 'authentication failure' /var/log/secure | awk '{ print $13 }' | cut -b7- | sort | uniq -c | xargs)"
echo "Latest login : $(last | grep root | grep -v tty | awk '{print $3}' | head -n 1)"
echo "Version      : v$version"
echo "Huong dan    : https://larvps.com/pages/documentation"
echo "Active Key   : https://larvps.com/pages/pricing"
echo "-------------------------------------------------------------------------"
fi

if [[ "$alert_login_ssh" = "1" ]]; then
client_ip=$(echo $SSH_CLIENT | awk '{ print $1}')
hostname=$(hostname -f)
vps_ip=$(hostname -I | awk '{print $1}')
date="$(date "+%d-%m-%Y %H:%M")"
info_ip=https://ipinfo.io/${client_ip}
text="
Cảnh báo Login SSH - ${vps_ip}
---------------------------
IP login: *${client_ip}* - [Chi tiết](${info_ip})
Hostname: ${hostname}
Ngày: ${date}
"
url="https://api.telegram.org/bot${telegram_api}/sendMessage"
curl -s -d "chat_id=$telegram_user_id&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url > /dev/null	
fi


if [ "$EUID" -ne 0 ]; then
clear
current_user=$(who | awk -F ' ' '{print $1}')
ip=$(curl -s https://larvps.com/scripts/ip-address)
echo "-------------------------------------------------------------------------"
echo "Da chuyen sang user Root."
echo "-------------------------------------------------------------------------"
echo "TH1: Neu ban muon dung user Root de SSH"
echo "- Go passwd de tao mat khau user Root"
echo "- Ket noi SSH: ssh root@$ip"
echo "TH2: Mac dinh SSH theo user $current_user"
echo "- Ket noi SSH: ssh $current_user@$ip"
echo "-------------------------------------------------------------------------"
echo
echo "sudo -i" >> "/home/$current_user/.bashrc"
sudo -i
fi




