#!/bin/bash
echo
echo "==//====================================================================="
echo "14. Quan ly Swap"
echo "/-----------------------------------------------------------------------/"
echo
options=("Xem Swap" "Them Swap" "Xoa Swap")
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/swap/list'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/swap/create'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/swap/delete'
            ;;
        *) larvps;;
    esac
done

