#!/bin/bash
echo
echo "==//====================================================================="
echo "18. Quan ly Wordpress"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Clear Cache All Domains"
    "Clear Cache One Domain"
    "Update All Domains (Core + Theme + Plugin)"
    "Update One Domain (Core + Theme + Plugin)"
    "Update Wordpress Core"
    "Update Theme"
    "Update Plugin"
    "Delete inActive (Theme + Plugin)"
    "Delete Post (Draft + Trash + Revision)"
    "Delete Comment (Spam)"
    "Clean WP-Rocket (Cache + Preload)"
    "Support Webp - Nginx"
    "Move wp-config.php outside public_html"
    "Disable File Mods + File Edit trong wp-config.php"
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            "/etc/larvps/menu/action/wp_manager/clear_cache_all"
            ;;
        "${options[1]}")
            "/etc/larvps/menu/action/wp_manager/clear_cache"
            ;;
        "${options[2]}")
            "/etc/larvps/menu/action/wp_manager/update_all"
            ;;
        "${options[3]}")
            "/etc/larvps/menu/action/wp_manager/update_domain"
            ;;
        "${options[4]}")
            "/etc/larvps/menu/action/wp_manager/update_wp_core"
            ;;
        "${options[5]}")
            "/etc/larvps/menu/action/wp_manager/update_theme"
            ;;
        "${options[6]}")
            "/etc/larvps/menu/action/wp_manager/update_plugin"
            ;;

        "${options[7]}")
            "/etc/larvps/menu/action/wp_manager/delete_unused_inactive"
            ;;

        "${options[8]}")
            "/etc/larvps/menu/action/wp_manager/delete_post_draft"
            ;;
        "${options[9]}")
            "/etc/larvps/menu/action/wp_manager/delete_comment_spam"
            ;;
        "${options[10]}")
            "/etc/larvps/menu/action/wp_manager/clean_cache_wprocket"
            ;;
        "${options[11]}")
            "/etc/larvps/menu/action/wp_manager/support_webp"
            ;;
        "${options[12]}")
            "/etc/larvps/menu/action/wp_manager/move_wp_config"
            ;;
        "${options[13]}")
            "/etc/larvps/menu/action/wp_manager/disable_mods_edit"
            ;;
        *) larvps;;
    esac
done