#!/bin/bash
CPU_USAGE=$(uptime | cut -d"," -f4 | cut -d":" -f2 | cut -d" " -f2 | sed -e "s/\0.//g")
CPU_USAGE_THRESHOLD=75
CPU_LIMIT=80
if [ $CPU_USAGE -gt $CPU_USAGE_THRESHOLD ] ; then
        CPU=$(ps -eo pcpu | sort -k 1 -r | grep -v %CPU | head -n 1 |sed -e "s/\.[0-9]//g")
        if [ $CPU -gt $CPU_LIMIT ]; then
                PIDCPU=$(ps -eo pid -eo pcpu | sort -k 2 -r | grep -v %CPU | head -n 1 | awk '{print $1}')
                cpulimit --pid $PIDCPU  --limit $CPU_LIMIT  -k
                echo system overloading!
                echo Top-most process killed $TOPPROCESS
                echo CPU USAGE is at $CPU_LOAD
        else
                exit 0
      fi
else
  exit 0
fi
