#!/bin/bash
#######################################################
# MBScript main menu
#######################################################
. /usr/local/mbmenu/functions #goi chuc nang


if [[ ! $1 ]]; then
   clear
fi
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo "//---------------------------------------------------------------------//"
echo
options=(
    "Quan ly Ten mien" #0
    "Quan ly SSL" #1
    "Quan ly SSH/SFTP" #2
    "Quan ly FTP Accounts" #3
    "Quan ly Database" #4
    "Quan ly PHP" #5
    "Quan ly Apache" #6
    "Thiet lap Backup" #7
    "Thiet lap AutoCheck" #8
)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [Ctrl+C=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/usr/local/mbmenu/mbdomain'
            ;;
        "${options[1]}")
            '/usr/local/mbmenu/mbssl'
            ;;
        "${options[2]}")
            '/usr/local/mbmenu/mbssh'
            ;;
        "${options[3]}")
            '/usr/local/mbmenu/mbftp'
			;;
        "${options[4]}")
            '/usr/local/mbmenu/mbdatabase'
            ;;
        "${options[5]}")
            '/usr/local/mbmenu/mbphp'
            ;;
        "${options[6]}")
            '/usr/local/mbmenu/mbapache'
            ;;
	"${options[7]}")
            '/usr/local/mbmenu/mbbackup'
            ;;
	"${options[8]}")
	 '/usr/local/mbmenu/mbautocheck'
	 ;;
        *) exit 1;;
    esac
done
#"Thiet lap AutoCheck" #8
