#!/bin/bash
#######################################################
# MBScript main menu
#######################################################
. /usr/local/mbmenu/func
if [[ ! $1 ]]; then
   clear
fi
echo "      __  __       _   ____               _   _ ______ _______ "
echo "     |  \/  |     | | |  _ \             | \ | |  ____|__   __|"
echo "     | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   "
echo "     | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   "
echo "     | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   "
echo "     |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   "
echo ""
echo "========================================================================="
echo "                MBScript v$version - Công cụ Quản lý máy chủ"
echo "-------------------------------------------------------------------------"
echo "Disk: ${use_disk}/${total_disk} GB | FreeInodes: ${free_inode} | Ram: ${use_ram}/${total_ram} MB | LoadAvg(5m): $loadavg "
echo "-------------------------------------------------------------------------"
echo "Hướng dẫn: /documentation"
echo "-------------------------------------------------------------------------"
echo
options=(
    "Quản lý tên miền"
    "Quản lý SSL"
    "Quản lý SSH/SFTP"
    "Quản lý FTP Accounts"
    "Quản lý Database"
    "Quản lý Services"
)
PS3="
$arrow Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/usr/local/mbmenu/mbdomain'
            ;;
        "${options[1]}")
            '/usr/local/mbmenu/mbssl'
            ;;
        "${options[2]}")
            '/usr/local/mbmenu/mbssh'
            ;;
        "${options[3]}")
            '/usr/local/mbmenu/mbftp'
			;;
        "${options[4]}")
            '/usr/local/mbmenu/mbdatabase'
            ;;
        "${options[5]}")
            '/usr/local/mbmenu/mbservice'
            ;;
        *) exit 1;;
    esac
done
