#!/bin/bash
#######################################################
# MBScript main menu
#######################################################
. /usr/local/mbmenu/functions #goi chuc nang
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8

if [[ ! $1 ]]; then
   clear
fi
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Công cụ Quản lý máy chủ"
echo "-------------------------------------------------------------------------"
echo "Trạng thái: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | CPU: $cpu
echo "-------------------------------------------------------------------------"
echo "Hướng dẫn: /documentation"
echo "//---------------------------------------------------------------------//"
echo
options=(
    "Quản lý tên miền" #0
    "Quản lý  SSL" #1
    "Quản lý  SSH/SFTP" #2
    "Quản lý  FTP Accounts" #3
    "Quản lý  Database" #4
    "Quản lý  PHP" #5
    "Quản lý  Apache" #6
    "Thiết lập Backup" #7
    "Thiết lập AutoCheck" #8
)
PS3="
-//- Nhập lựa chọn của bạn (1-${#options[@]}) [Ctrl+C=Thoát]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/usr/local/mbmenu/mbdomain'
            ;;
        "${options[1]}")
            '/usr/local/mbmenu/mbssl'
            ;;
        "${options[2]}")
            '/usr/local/mbmenu/mbssh'
            ;;
        "${options[3]}")
            '/usr/local/mbmenu/mbftp'
			;;
        "${options[4]}")
            '/usr/local/mbmenu/mbdatabase'
            ;;
        "${options[5]}")
            '/usr/local/mbmenu/mbphp'
            ;;
        "${options[6]}")
            '/usr/local/mbmenu/mbapache'
            ;;
	"${options[7]}")
            '/usr/local/mbmenu/mbbackup'
            ;;
	"${options[8]}")
	 '/usr/local/mbmenu/mbautocheck'
	 ;;
        *) exit 1;;
    esac
done
