#!/bin/bash
#######################################################
# MBScript main menu
#######################################################
. /usr/local/mbmenu/functions #goi chuc nang


if [[ ! $1 ]]; then
   clear
fi
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "Huong dan: /check cpu > 90% , ram> 90 % , apache, mysql and restar when stop.  "
echo "//---------------------------------------------------------------------//"
echo
options=(
    "Cai dat mbAutocheck" #0
    "Xoa MbAutoCheck" #1
    "Quay lai" #2
)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [Ctrl+C=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/usr/local/mbmenu/action/autocheck/create_autocheck'
            ;;
        "${options[1]}")
            '/usr/local/mbmenu/action/autocheck/delete_autocheck'
            ;;
        "${options[3]}")
        '/usr/local/bin/mb'
        ;;
        *) exit 1;;
    esac
 done
