#!/bin/bash
#######################################################
# MBScript main menu
#######################################################
. /usr/local/mbmenu/functions #goi chuc nang


if [[ ! $1 ]]; then
   clear
fi
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "- 5. Quan ly Database - MariaDB: $(mysql --version | cut -f6 -d' ' | cut -f1 -d'-') - $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo "//---------------------------------------------------------------------//"
echo
options=(
    "Tao Databse va User" #0
    "Thay doi Password User" #1
    "Xoa Database" #2
    "Danh sach Database" #3
    "Quay lai" #4
)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [Ctrl+C=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/usr/local/mbmenu/action/database/create_database_user'
            ;;
        "${options[1]}")
            '/usr/local/mbmenu/action/database/change_password_user'
            ;;
        "${options[2]}")
            '/usr/local/mbmenu/action/database/delete_database'
            ;;
        "${options[3]}")
            '/usr/local/mbmenu/action/database/list_database'
            ;;
        "${options[4]}")
        '/usr/local/bin/mb'
        ;;
        *) exit 1;;
    esac
done
                                        
