#!/bin/bash
#######################################################
# MBScript main menu
#######################################################
. /usr/local/mbmenu/functions #goi chuc nang

if [[ ! $1 ]]; then
   clear
fi

clear
echo "#    __  __       _   ____               _   _ ______ _______ #"
echo "#   |  \/  |     | | |  _ \             | \ | |  ____|__   __|#"
echo "#   | \  / | __ _| |_| |_) | __ _  ___  |  \| | |__     | |   #"
echo "#   | |\/| |/ _  | __|  _ < / _  |/ _ \ | .   |  __|    | |   #"
echo "#   | |  | | (_| | |_| |_) | (_| | (_) _| |\  | |____   | |   #"
echo "#   |_|  |_|\__,_|\__|____/ \__,_|\___(_|_| \_|______|  |_|   #"
echo ""
echo "========================================================================="
echo "                MBScript v$version - Cong cu quan ly VPS"
echo "                      MBscript URL"
echo "-------------------------------------------------------------------------"
echo "Status: $status | Disk: ${use_disk}/${total_disk} GB | Ram: ${use_ram}/${total_ram} MB | Swap: ${use_swap}/${total_swap} MB"
echo "-------------------------------------------------------------------------"
echo "- Quan ly SSL : $(apache2 -v | cut -f3 -d' ' | head -1) - $(systemctl status apache2.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------------------------------------------------"
echo "Huong dan: /documentation"
echo "//---------------------------------------------------------------------//"
echo

options=(
    "Cai SSL mien phi" #1
    "Cai SSL paid" #2
    "List SSL Free" #3
    "List SSL Paid" #5
    "Quay lai"

)
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [Ctrl+C=Thoat]: "
select opt in "${options[@]}"
do
        case $opt in
        "${options[0]}")
            '/usr/local/mbmenu/action/ssl/free_ssl'
            ;;
                "${options[1]}")
            '/usr/local/mbmenu/action/ssl/paid_ssl'
            ;;
                "${options[2]}")
            '/usr/local/mbmenu/action/ssl/listssllet'
            ;;
            "${options[3]}")
            '/usr/local/mbmenu/action/ssl/listsslpaid'
            ;;
            "${options[4]}")
            '/usr/local/mbmenu/mb'
            ;;


        *) exit 1;;
    esac
done
