# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        run:#!/bin/bash
echo
echo "==//====================================================================="
echo "1. Quan ly Domain"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://larvps.com/pages/documentation/all#section-5"
echo "/-----------------------------------------------------------------------/"
echo
options=(
    "Danh sach - Domain/SubDomain"
    "Them - Domain/SubDomain"
    "Them - Redirect"
    "Them - Alias"
    "Phan quyen han (Chown/Chmod)"
    "Xoa"
    "Mo/Khoa"
    "Phuc hoi Nginx"
    )
PS3="
-//- Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"
do
    case $opt in
        "${options[0]}")
            '/etc/larvps/menu/action/domain/list'
            ;;
        "${options[1]}")
            '/etc/larvps/menu/action/domain/create'
            ;;
        "${options[2]}")
            '/etc/larvps/menu/action/domain/redirect'
            ;;
        "${options[3]}")
            '/etc/larvps/menu/action/domain/alias'
            ;;
        "${options[4]}")
            '/etc/larvps/menu/permission'
            ;;
        "${options[5]}")
            '/etc/larvps/menu/action/domain/delete'
            ;;
        "${options[6]}")
            '/etc/larvps/menu/action/domain/suspend'
            ;;
        "${options[7]}")
            '/etc/larvps/menu/action/domain/restore_nginx'
            ;;
        *) clear && larvps;;
    esac
done

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
